'use strict';

module.exports = {
  ad: 'العربية',
  yon: 'rtl',
  yerel: 'ar',
  metin: {
    'menu.dosya': 'ملف',
    'menu.yeniSekme': 'علامة تبويب جديدة',
    'menu.sekmeyiKapat': 'إغلاق علامة التبويب',
    'menu.adresCubugu': 'الانتقال إلى شريط العنوان',
    'menu.sayfadaBul': 'بحث في الصفحة',
    'menu.cikis': 'خروج',
    'menu.duzen': 'تحرير',
    'menu.geriAl': 'تراجع',
    'menu.yinele': 'إعادة',
    'menu.kes': 'قص',
    'menu.kopyala': 'نسخ',
    'menu.yapistir': 'لصق',
    'menu.tumunuSec': 'تحديد الكل',
    'menu.gorunum': 'عرض',
    'menu.yenile': 'إعادة تحميل',
    'menu.onbelleksizYenile': 'إعادة تحميل مع تجاهل الذاكرة المؤقتة',
    'menu.yakinlastir': 'تكبير',
    'menu.uzaklastir': 'تصغير',
    'menu.normalBoyut': 'الحجم الفعلي',
    'menu.tamEkran': 'ملء الشاشة',
    'menu.gelistirici': 'أدوات المطور',
    'menu.arayuzGelistirici': 'أدوات مطور الواجهة',
    'menu.gecmis': 'السجل',
    'menu.geri': 'رجوع',
    'menu.ileri': 'تقدم',
    'menu.gecmisiGoster': 'عرض السجل',
    'menu.indirilenler': 'التنزيلات',
    'menu.yerImleri': 'المفضلة',
    'menu.yerImiEkle': 'إضافة هذه الصفحة إلى المفضلة',
    'menu.yerImleriniGoster': 'عرض المفضلة',
    'menu.yerImleriCubugu': 'شريط المفضلة',
    'menu.sekmeler': 'علامات التبويب',
    'menu.sonrakiSekme': 'علامة التبويب التالية',
    'menu.oncekiSekme': 'علامة التبويب السابقة',
    'menu.nSekme': 'علامة التبويب {n}',
    'menu.sonSekme': 'آخر علامة تبويب',
    'menu.yardim': 'مساعدة',
    'menu.ayarlar': 'الإعدادات',
    'menu.hakkinda': 'حول Girginos Browser',
    'hakkinda.detay': 'متصفح يركّز على الخصوصية.',
    'menu.yazdir': 'طباعة…',
    'menu.sayfayiKaydet': 'حفظ الصفحة باسم…',
    'menu.digerAraclar': 'أدوات أخرى',
    'menu.yakinlastirma': 'التكبير',
    'menu.veriSil': 'حذف بيانات التصفح…',
    'arac.menu': 'القائمة',

    'baglam.baglantiYeniSekme': 'فتح الرابط في علامة تبويب جديدة',
    'baglam.baglantiKopyala': 'نسخ عنوان الرابط',
    'baglam.gorselYeniSekme': 'فتح الصورة في علامة تبويب جديدة',
    'baglam.gorselKopyala': 'نسخ عنوان الصورة',
    'baglam.gorselKaydet': 'حفظ الصورة',
    'baglam.ara': 'البحث عن «{q}»',
    'baglam.kaynak': 'عرض مصدر الصفحة',
    'baglam.incele': 'فحص العنصر',

    'dialog.iptal': 'إلغاء',
    'dialog.ac': 'فتح',
    'dialog.disBaslik': 'الخروج من Girginos Browser',
    'dialog.disMesaj': 'سيُفتح رابط «{sema}» في تطبيق آخر.',
    'dialog.reddet': 'حظر',
    'dialog.izinVer': 'سماح',
    'dialog.izinBaslik': 'طلب إذن',
    'dialog.izinMesaj': '{origin} يطلب:',
    'dialog.izinHatirla': 'تذكّر اختياري لهذا الموقع',
    'dialog.calistirBaslik': 'هذا الملف قابل للتنفيذ',
    'dialog.calistirMesaj': 'قد يضر هذا الملف بجهازك.',
    'dialog.calistirDevam': 'تشغيل على أي حال',
    'dialog.kaynak': 'المصدر',

    'izin.notifications': 'إرسال الإشعارات',
    'izin.geolocation': 'معرفة موقعك',
    'izin.media': 'الكاميرا والميكروفون',
    'izin.midi': 'أجهزة MIDI',
    'izin.midiSysex': 'أجهزة MIDI',
    'izin.clipboard-read': 'قراءة الحافظة',
    'izin.display-capture': 'مشاركة الشاشة',
    'izin.openExternal': 'فتح تطبيق آخر',
    'izin.idle-detection': 'كشف الخمول',
    'izin.pointerLock': 'حجز مؤشر الفأرة',
    'izin.fullscreen': 'ملء الشاشة',

    'arac.geri': 'رجوع',
    'arac.ileri': 'تقدم',
    'arac.yenile': 'إعادة تحميل',
    'arac.durdur': 'إيقاف',
    'arac.anasayfa': 'الصفحة الرئيسية',
    'arac.yeniSekme': 'علامة تبويب جديدة',
    'arac.sekmeyiKapat': 'إغلاق علامة التبويب',
    'arac.gecmis': 'السجل',
    'arac.indirilenler': 'التنزيلات',
    'arac.ayarlar': 'الإعدادات',
    'arac.adresIpucu': 'ابحث أو اكتب عنوانًا',
    'arac.yerImiEkle': 'إضافة إلى المفضلة',
    'arac.yerImiCikar': 'إزالة من المفضلة',
    'arac.kalkanAcik': 'تم حظر {n} من المتعقّبات — انقر للإيقاف',
    'arac.kalkanKapali': 'الحظر متوقف في هذا الموقع — انقر للتشغيل',
    'arac.guvenli': 'الاتصال مشفّر (HTTPS)',
    'arac.guvensiz': 'الاتصال غير مشفّر',
    'arac.yeniSekmeBaslik': 'علامة تبويب جديدة',
    'arac.adsiz': 'بدون عنوان',

    'bul.ipucu': 'بحث في الصفحة',
    'bul.onceki': 'السابق',
    'bul.sonraki': 'التالي',
    'bul.kapat': 'إغلاق',

    'panel.gecmis': 'السجل',
    'panel.yerImleri': 'المفضلة',
    'panel.indirilenler': 'التنزيلات',
    'panel.ayarlar': 'الإعدادات',
    'panel.kapat': 'إغلاق اللوحة',
    'panel.kaldir': 'إزالة',
    'gecmis.ara': 'ابحث في السجل',
    'gecmis.temizle': 'مسح السجل',
    'gecmis.bos': 'السجل فارغ.',
    'gecmis.eslesmeYok': 'لا توجد نتائج مطابقة.',
    'gecmis.bugun': 'اليوم',
    'gecmis.dun': 'أمس',
    'yerimi.bos': 'لا توجد لديك مفضلة بعد.',
    'yerimi.cubukBos': 'لا توجد مفضلة — اضغط Ctrl+D لإضافة هذه الصفحة',
    'yerimi.tumu': 'كل المفضلة',
    'yerimi.ac': 'فتح',
    'yerimi.yeniSekmedeAc': 'فتح في علامة تبويب جديدة',
    'yerimi.adresiKopyala': 'نسخ العنوان',
    'yerimi.duzenle': 'إعادة التسمية…',
    'yerimi.cubuguGizle': 'إخفاء شريط المفضلة',

    'indirme.bos': 'لا توجد تنزيلات بعد.',
    'indirme.devam': 'جارٍ التنزيل',
    'indirme.tamam': 'اكتمل',
    'indirme.iptal': 'أُلغي',
    'indirme.hata': 'فشل',
    'indirme.kesildi': 'انقطع',
    'indirme.ac': 'فتح',
    'indirme.klasor': 'إظهار في المجلد',
    'indirme.tumunuGoster': 'عرض الكل',

    'ayar.engellenenSayi': 'المتعقّبات المحظورة حتى الآن',
    'ayar.yukluAlan': 'النطاقات المحمّلة من القوائم',
    'ayar.yerImiSayi': 'المفضلة',
    'ayar.bolumArama': 'البحث وبدء التشغيل',
    'ayar.dil': 'اللغة',
    'ayar.dilAciklama': 'تستخدم القوائم واللوحات وصفحات الخطأ هذه اللغة.',
    'ayar.dilSistem': 'لغة النظام',
    'ayar.aramaMotoru': 'محرك البحث',
    'ayar.aramaMotoruAciklama': 'عمليات البحث المكتوبة في شريط العنوان تذهب إلى هنا.',
    'ayar.anasayfa': 'الصفحة الرئيسية',
    'ayar.anasayfaAciklama': 'العنوان الذي يفتحه زر الصفحة الرئيسية.',
    'ayar.anasayfaIpucu': 'اتركه فارغًا لصفحة علامة التبويب الجديدة',
    'ayar.bolumGizlilik': 'الخصوصية',
    'ayar.engelleyici': 'حاجب المتعقّبات والإعلانات',
    'ayar.engelleyiciAciklama': 'يلغي الطلبات إلى نطاقات الإعلانات والتتبع المعروفة.',
    'ayar.dnt': 'إرسال إشارة عدم التتبع',
    'ayar.dntAciklama': 'يضيف ترويسات DNT و Sec-GPC إلى كل طلب.',
    'ayar.gecmisiKaydet': 'حفظ السجل',
    'ayar.gecmisiKaydetAciklama': 'عند الإيقاف لا تُكتب الصفحات المزارة على القرص.',
    'ayar.cerezler': 'الكوكيز والذاكرة المؤقتة',
    'ayar.cerezlerAciklama': 'يحذف الكوكيز والتخزين المحلي والذاكرة المؤقتة لكل المواقع.',
    'ayar.veriTemizle': 'مسح البيانات',
    'ayar.temizleniyor': 'جارٍ المسح…',
    'ayar.temizlendi': 'تم المسح',
    'ayar.siteIzinleri': 'أذونات المواقع',
    'ayar.siteIzinleriAciklama': 'يحذف القرارات المحفوظة للموقع والكاميرا والإشعارات، واستثناءات الحاجب.',
    'ayar.izinSifirla': 'إعادة تعيين أذونات المواقع',
    'ayar.sifirlandi': 'أُعيد التعيين',
    'ayar.bolumListeler': 'قوائم التصفية',
    'ayar.listeKullan': 'استخدام القوائم المنزّلة',
    'ayar.listeKullanAciklama': 'تُحجب أيضًا نطاقات قوائم مثل EasyList. عند الإيقاف تعمل القائمة المدمجة فقط.',
    'ayar.otomatikGuncelle': 'التحديث التلقائي',
    'ayar.otomatikGuncelleAciklama': 'تُحدَّث القوائم في الخلفية بالفترة التي تحددها (عادة كل 4 أيام).',
    'ayar.listeYenile': 'تحديث القوائم',
    'ayar.listeYenileAciklama': 'ينزّلها كلها من جديد فورًا.',
    'ayar.simdiGuncelle': 'حدّث الآن',
    'ayar.guncelleniyor': 'جارٍ التحديث…',
    'ayar.listeEkle': 'أضف قائمتك',
    'ayar.listeEkleAciklama': 'عنوان https بصيغة Adblock Plus أو hosts أو قائمة نطاقات بسيطة.',
    'ayar.listeEkleIpucu': 'https://... عنوان قائمة التصفية',
    'ayar.ekle': 'إضافة',
    'ayar.ekleniyor': 'جارٍ الإضافة…',
    'ayar.listeKaldir': 'إزالة',
    'ayar.listeIndirilmedi': 'لم تُنزَّل بعد',
    'ayar.listeHata': 'تعذّر التحديث: {hata}',
    'ayar.listeDurum': '{n} نطاقًا · حُدِّثت {ne}',
    'ayar.bugun': 'اليوم',
    'ayar.dun': 'أمس',
    'ayar.gunOnce': 'قبل {n} يومًا',
    'ayar.bolumIzinler': 'طلبات الأذونات',
    'ayar.izinSor': 'اسأل في كل مرة',
    'ayar.izinVer': 'السماح دائمًا',
    'ayar.izinRet': 'الحظر دائمًا',
    'ayar.izinSatir': 'ماذا يحدث عندما يطلب موقع {izin}؟',
    'ayar.bolumGorunum': 'المظهر',
    'ayar.yerImleriCubugu': 'شريط المفضلة',
    'ayar.yerImleriCubuguAciklama': 'يعرض المفضلة أسفل شريط الأدوات.',
    'ayar.yenidenBaslat': 'أعد تشغيل Girginos Browser لتطبيق اللغة.',

    'liste.easylist': 'الإعلانات',
    'liste.easyprivacy': 'المتعقّبات',
    'liste.hataHttps': 'يمكن إضافة عناوين https:// فقط.',
    'liste.hataVar': 'هذه القائمة مضافة بالفعل.',
    /* --- site bilgisi menusu --- */
    'site.baglantiGuvenli': 'الاتصال آمن',
    'site.baglantiGuvensiz': 'الاتصال غير آمن',
    'site.guvensizUyari': 'تُرسل المعلومات التي تُدخلها في هذه الصفحة دون تشفير.',
    'site.sertifikaVeren': 'جهة الإصدار: {ad}',
    'site.sertifikaSahip': 'صادرة إلى: {ad}',
    'site.sertifikaGecerlilik': 'الصلاحية: {bas} – {bit}',
    'site.parmakIzi': 'نسخ البصمة',
    'site.sertifikaYok': 'لا توجد معلومات عن الشهادة',
    'site.cerezler': 'الكوكيز وبيانات الموقع',
    'site.cerezSayisi': '{n} كوكي',
    'site.veriSil': 'حذف بيانات هذا الموقع',
    'site.engelleyici': 'حجب المتعقّبات',
    'site.izinSifirla': 'إعادة تعيين أذونات هذا الموقع',
    'site.ayarlar': 'إعدادات الموقع',
    /* --- guncelleme --- */
    'menu.guncellemeDenetle': 'التحقق من التحديثات',
    'ayar.bolumGuncelleme': 'التحديثات',
    'ayar.surum': 'الإصدار',
    'ayar.guncellemeKontrolEt': 'تحقّق الآن',
    'ayar.guncellemeIndirDugme': 'تنزيل',
    'ayar.guncellemeKur': 'أعد التشغيل وثبّت',
    'ayar.guncellemeOtoKontrol': 'التحقق من التحديثات تلقائيًا',
    'ayar.guncellemeOtoKontrolAciklama': 'يُتحقَّق من معلومات الإصدار الموقّعة عند البدء وكل 6 ساعات.',
    'ayar.guncellemeOtoIndir': 'التنزيل تلقائيًا',
    'ayar.guncellemeOtoIndirAciklama': 'يُنزَّل الإصدار الجديد في الخلفية؛ ويظل التثبيت بحاجة إلى موافقتك.',
    'ayar.guncellemeKanal': 'قناة التحديث',
    'ayar.guncellemeKanalAciklama': 'قناة بيتا تحصل على الجديد مبكرًا وهي أقل اختبارًا.',
    'ayar.kanalKararli': 'مستقرة',
    'ayar.kanalBeta': 'بيتا',
    'guncelleme.kapali': 'التحديثات متوقفة: لم يُضبط مفتاح الإصدار أو عنوان التغذية.',
    'guncelleme.paketlenmemis': 'التشغيل من المصدر؛ التحديثات تنطبق على النسخة المثبّتة فقط.',
    'guncelleme.bosta': 'لم يتم التحقق بعد.',
    'guncelleme.kontrol': 'جارٍ التحقق…',
    'guncelleme.guncel': 'أنت تستخدم أحدث إصدار.',
    'guncelleme.bulundu': 'الإصدار {surum} متاح.',
    'guncelleme.iniyor': 'جارٍ التنزيل… {n}٪',
    'guncelleme.hazir': 'الإصدار {surum} جاهز للتثبيت.',
    'guncelleme.hata': 'تعذّر التحقق: {sebep}',
    /* --- yeni sekme ve hata sayfasi --- */
    'sayfa.tekrarDene': 'أعد المحاولة',
    'sayfa.oneriYenile': 'أعد تحميل الصفحة',
    'sayfa.oneriAdres': 'تحقّق من العنوان بحثًا عن أخطاء إملائية',
    'sayfa.oneriBaglanti': 'تحقّق من اتصالك بالإنترنت',
    'sayfa.oneriBilgiGirme': 'لا تُدخل معلومات حسّاسة هنا',
    'hata.dns.baslik': 'لم يُعثر على الخادم',
    'hata.dns.metin': 'تعذّر تحويل هذا العنوان إلى IP. قد يكون النطاق مكتوبًا خطأ أو غير متاح.',
    'hata.cevrimdisi.baslik': 'لا يوجد اتصال بالإنترنت',
    'hata.cevrimdisi.metin': 'لا يبدو أن جهازك متصل بشبكة.',
    'hata.baglanti.baslik': 'تعذّر الاتصال',
    'hata.baglanti.metin': 'رفض الخادم الاتصال أو انقطع الاتصال بشكل غير متوقع.',
    'hata.zamanAsimi.baslik': 'انتهت مهلة الاتصال',
    'hata.zamanAsimi.metin': 'لم يستجب الخادم خلال وقت معقول.',
    'hata.sertifikaAd.baslik': 'الشهادة لا تخص هذا الموقع',
    'hata.sertifikaAd.metin': 'النطاق في شهادة الخادم لا يطابق العنوان الذي أدخلته.',
    'hata.sertifikaSure.baslik': 'انتهت صلاحية الشهادة',
    'hata.sertifikaSure.metin': 'لم تعد شهادة أمان الخادم صالحة. تحقّق أيضًا من تاريخ جهازك.',
    'hata.sertifikaMakam.baslik': 'تعذّر التحقق من الشهادة',
    'hata.sertifikaMakam.metin': 'الجهة التي وقّعت الشهادة غير معروفة. قد يكون الاتصال معترضًا.',
    'hata.cokme.baslik': 'توقفت علامة التبويب عن الاستجابة',
    'hata.cokme.metin': 'أُغلقت الصفحة بشكل غير متوقع.',
    'hata.bilinmeyen.baslik': 'تعذّر فتح هذه الصفحة',
    'hata.bilinmeyen.metin': 'حدثت مشكلة غير معروفة أثناء تحميل الصفحة.',
    'yenisekme.ara': 'بحث',
    'yenisekme.sik': 'الأكثر زيارة',
    'yenisekme.oneCikan': 'مميّز',
    'yenisekme.kisayolEkle': '+ إضافة اختصار',
    'yenisekme.kisayolIpucu': 'mithal.com — اضغط Enter للإضافة',
    'yenisekme.gecersizAdres': 'أدخل عنوانًا صالحًا',
    'yenisekme.kisayol': 'اختصار',
    'yenisekme.bosNot': 'ستظهر هنا المواقع التي تزورها أكثر أثناء تصفّحك.',
    'yenisekme.engellendi': 'حجب Girginos Browser حتى الآن {n} من طلبات التعقّب.',
    'yenisekme.engelleyiciAcik': 'حجب المتعقّبات مفعّل. ستُحسب الطلبات المحجوبة هنا.',
    /* --- adres onerileri --- */
    'oneri.ara': 'البحث باستخدام {motor}',
    'oneri.adreseGit': 'الانتقال إلى العنوان',
    /* --- gorunum --- */
    'ayar.tema': 'المظهر',
    'ayar.temaAciklama': 'تتبع الواجهة والصفحات الداخلية والقوائم هذا الاختيار.',
    'ayar.temaSistem': 'حسب النظام',
    'ayar.temaAcik': 'فاتح',
    'ayar.temaKoyu': 'داكن',
    /* --- katman: izin kutusu --- */
    'dialog.izinIstiyor': 'يطلب:',
    'izin.storage-access': 'الوصول إلى التخزين',
    /* --- site izin duvari --- */
    'panel.siteIzinleri': 'أذونات الموقع',
    'izin.siteYok': 'لا توجد أذونات لهذه الصفحة.',
    'izin.durumSor': 'اسأل',
    'izin.durumIzin': 'السماح',
    'izin.durumRet': 'حظر',
    'izin.varsayilanEk': 'افتراضي',
    'izin.siteKarari': 'حددته لهذا الموقع.',
    'izin.varsayilanIzleniyor': 'يُطبَّق الإعداد العام.',
    'izin.bilinmeyen': 'هذا الإذن ({ad})'
  }
};
