'use strict';

module.exports = {
  ad: 'English',
  yon: 'ltr',
  yerel: 'en-US',
  metin: {
    'menu.dosya': 'File',
    'menu.yeniSekme': 'New tab',
    'menu.sekmeyiKapat': 'Close tab',
    'menu.adresCubugu': 'Focus address bar',
    'menu.sayfadaBul': 'Find in page',
    'menu.cikis': 'Quit',
    'menu.duzen': 'Edit',
    'menu.geriAl': 'Undo',
    'menu.yinele': 'Redo',
    'menu.kes': 'Cut',
    'menu.kopyala': 'Copy',
    'menu.yapistir': 'Paste',
    'menu.tumunuSec': 'Select all',
    'menu.gorunum': 'View',
    'menu.yenile': 'Reload',
    'menu.onbelleksizYenile': 'Reload ignoring cache',
    'menu.yakinlastir': 'Zoom in',
    'menu.uzaklastir': 'Zoom out',
    'menu.normalBoyut': 'Actual size',
    'menu.tamEkran': 'Full screen',
    'menu.gelistirici': 'Developer tools',
    'menu.arayuzGelistirici': 'Browser UI developer tools',
    'menu.gecmis': 'History',
    'menu.geri': 'Back',
    'menu.ileri': 'Forward',
    'menu.gecmisiGoster': 'Show history',
    'menu.indirilenler': 'Downloads',
    'menu.yerImleri': 'Bookmarks',
    'menu.yerImiEkle': 'Bookmark this page',
    'menu.yerImleriniGoster': 'Show bookmarks',
    'menu.yerImleriCubugu': 'Bookmarks bar',
    'menu.sekmeler': 'Tabs',
    'menu.sonrakiSekme': 'Next tab',
    'menu.oncekiSekme': 'Previous tab',
    'menu.nSekme': 'Tab {n}',
    'menu.sonSekme': 'Last tab',
    'menu.yardim': 'Help',
    'menu.ayarlar': 'Settings',
    'menu.hakkinda': 'About Girginos Browser',
    'hakkinda.detay': 'A privacy-first browser.',
    'menu.yazdir': 'Print…',
    'menu.sayfayiKaydet': 'Save page as…',
    'menu.digerAraclar': 'More tools',
    'menu.yakinlastirma': 'Zoom',
    'menu.veriSil': 'Delete browsing data…',
    'arac.menu': 'Menu',

    'baglam.baglantiYeniSekme': 'Open link in new tab',
    'baglam.baglantiKopyala': 'Copy link address',
    'baglam.gorselYeniSekme': 'Open image in new tab',
    'baglam.gorselKopyala': 'Copy image address',
    'baglam.gorselKaydet': 'Save image',
    'baglam.ara': 'Search for "{q}"',
    'baglam.kaynak': 'View page source',
    'baglam.incele': 'Inspect element',

    'dialog.iptal': 'Cancel',
    'dialog.ac': 'Open',
    'dialog.disBaslik': 'Leave Girginos Browser',
    'dialog.disMesaj': 'This "{sema}" link will open in another application.',
    'dialog.reddet': 'Block',
    'dialog.izinVer': 'Allow',
    'dialog.izinBaslik': 'Permission request',
    'dialog.izinMesaj': '{origin} wants to use:',
    'dialog.izinHatirla': 'Remember my choice for this site',
    'dialog.calistirBaslik': 'This file is executable',
    'dialog.calistirMesaj': 'This file could harm your computer.',
    'dialog.calistirDevam': 'Run anyway',
    'dialog.kaynak': 'Source',

    'izin.notifications': 'notifications',
    'izin.geolocation': 'your location',
    'izin.media': 'camera and microphone',
    'izin.midi': 'MIDI devices',
    'izin.midiSysex': 'MIDI devices',
    'izin.clipboard-read': 'reading the clipboard',
    'izin.display-capture': 'screen sharing',
    'izin.openExternal': 'opening another application',
    'izin.idle-detection': 'idle detection',
    'izin.pointerLock': 'locking the mouse pointer',
    'izin.fullscreen': 'full screen',

    'arac.geri': 'Back',
    'arac.ileri': 'Forward',
    'arac.yenile': 'Reload',
    'arac.durdur': 'Stop',
    'arac.anasayfa': 'Home',
    'arac.yeniSekme': 'New tab',
    'arac.sekmeyiKapat': 'Close tab',
    'arac.gecmis': 'History',
    'arac.indirilenler': 'Downloads',
    'arac.ayarlar': 'Settings',
    'arac.adresIpucu': 'Search or enter address',
    'arac.yerImiEkle': 'Add bookmark',
    'arac.yerImiCikar': 'Remove bookmark',
    'arac.kalkanAcik': '{n} trackers blocked — click to turn off',
    'arac.kalkanKapali': 'Blocking is off for this site — click to turn on',
    'arac.guvenli': 'Connection is encrypted (HTTPS)',
    'arac.guvensiz': 'Connection is not encrypted',
    'arac.yeniSekmeBaslik': 'New tab',
    'arac.adsiz': 'Untitled',

    'bul.ipucu': 'Find in page',
    'bul.onceki': 'Previous',
    'bul.sonraki': 'Next',
    'bul.kapat': 'Close',

    'panel.gecmis': 'History',
    'panel.yerImleri': 'Bookmarks',
    'panel.indirilenler': 'Downloads',
    'panel.ayarlar': 'Settings',
    'panel.kapat': 'Close panel',
    'panel.kaldir': 'Remove',
    'gecmis.ara': 'Search history',
    'gecmis.temizle': 'Clear history',
    'gecmis.bos': 'Your history is empty.',
    'gecmis.eslesmeYok': 'No matching entries.',
    'gecmis.bugun': 'Today',
    'gecmis.dun': 'Yesterday',
    'yerimi.bos': 'You have no bookmarks yet.',
    'yerimi.cubukBos': 'No bookmarks — press Ctrl+D to add this page',
    'yerimi.tumu': 'All bookmarks',
    'yerimi.ac': 'Open',
    'yerimi.yeniSekmedeAc': 'Open in new tab',
    'yerimi.adresiKopyala': 'Copy address',
    'yerimi.duzenle': 'Rename…',
    'yerimi.cubuguGizle': 'Hide bookmarks bar',

    'indirme.bos': 'No downloads yet.',
    'indirme.devam': 'Downloading',
    'indirme.tamam': 'Completed',
    'indirme.iptal': 'Cancelled',
    'indirme.hata': 'Failed',
    'indirme.kesildi': 'Interrupted',
    'indirme.ac': 'Open',
    'indirme.klasor': 'Show in folder',
    'indirme.tumunuGoster': 'Show all',

    'ayar.engellenenSayi': 'Trackers blocked so far',
    'ayar.yukluAlan': 'Domains loaded from lists',
    'ayar.yerImiSayi': 'Bookmarks',
    'ayar.bolumArama': 'Search and startup',
    'ayar.dil': 'Language',
    'ayar.dilAciklama': 'Menus, panels and error pages use this language.',
    'ayar.dilSistem': 'System language',
    'ayar.aramaMotoru': 'Search engine',
    'ayar.aramaMotoruAciklama': 'Searches typed in the address bar go here.',
    'ayar.anasayfa': 'Home page',
    'ayar.anasayfaAciklama': 'The address opened by the home button.',
    'ayar.anasayfaIpucu': 'Leave empty for the new tab page',
    'ayar.bolumGizlilik': 'Privacy',
    'ayar.engelleyici': 'Tracker and ad blocker',
    'ayar.engelleyiciAciklama': 'Cancels requests to known advertising and tracking domains.',
    'ayar.dnt': 'Send do-not-track signal',
    'ayar.dntAciklama': 'Adds DNT and Sec-GPC headers to every request.',
    'ayar.ucuncuTarafCerez': 'Block third-party cookies',
    'ayar.ucuncuTarafCerezAciklama': 'The main carrier of cross-site tracking. If a site breaks, you can allow it from the lock menu in the address bar. Changing this setting takes full effect after a restart.',
    'ayar.kapanistaCerezSil': 'Delete cookies on exit',
    'ayar.kapanistaCerezSilAciklama': 'Cookies for bookmarked sites are kept, so you stay signed in there.',
    'ayar.gecmisiKaydet': 'Save history',
    'ayar.gecmisiKaydetAciklama': 'When off, visited pages are never written to disk.',
    'ayar.cerezler': 'Cookies and cache',
    'ayar.cerezlerAciklama': 'Deletes cookies, local storage and cache for all sites.',
    'ayar.veriTemizle': 'Clear data',
    'ayar.temizleniyor': 'Clearing…',
    'ayar.temizlendi': 'Cleared',
    'ayar.siteIzinleri': 'Site permissions',
    'ayar.siteIzinleriAciklama': 'Deletes remembered location, camera and notification choices, and blocker exceptions.',
    'ayar.izinSifirla': 'Reset site permissions',
    'ayar.sifirlandi': 'Reset',
    'ayar.bolumVekil': 'Proxy',
    'ayar.vekil': 'Proxy server',
    'ayar.vekilAciklama': 'Everything goes through the proxy: browsing, filter lists and updates. While a proxy is on, WebRTC cannot reveal your real address.',
    'ayar.vekilKapali': 'Off',
    'ayar.vekilSistem': 'System setting',
    'ayar.vekilElle': 'Manual',
    'ayar.vekilAdres': 'Address',
    'ayar.vekilAdresAciklama': 'For example socks5://127.0.0.1:9050 (Tor) or http://192.168.1.10:8080',
    'ayar.vekilAdresHatali': 'That address was not accepted and has not been saved. Format: socks5://host:port',
    'ayar.vekilReddedildi': 'The browser did not accept the proxy rule, so connections were pointed at an unreachable proxy. Check the address.',
    'ayar.vekilAtlaHatali': 'Some entries were not accepted. Each one must be a domain, *.example.com or 10.0.0.0/8.',
    'ayar.vekilAtla': 'Sites that skip the proxy',
    'ayar.vekilAtlaAciklama': 'These domains connect directly. Local addresses are always excluded.',
    'ayar.bolumListeler': 'Filter lists',
    'ayar.listeKullan': 'Use downloaded lists',
    'ayar.listeKullanAciklama': 'Domains from lists such as EasyList are blocked too. When off, only the built-in list applies.',
    'ayar.otomatikGuncelle': 'Update automatically',
    'ayar.otomatikGuncelleAciklama': 'Lists refresh in the background at the interval they declare (usually every 4 days).',
    'ayar.listeYenile': 'Refresh lists',
    'ayar.listeYenileAciklama': 'Downloads all of them again right now.',
    'ayar.simdiGuncelle': 'Update now',
    'ayar.guncelleniyor': 'Updating…',
    'ayar.listeEkle': 'Add your own list',
    'ayar.listeEkleAciklama': 'An https address in Adblock Plus, hosts or plain domain format.',
    'ayar.listeEkleIpucu': 'https://... filter list address',
    'ayar.ekle': 'Add',
    'ayar.ekleniyor': 'Adding…',
    'ayar.listeKaldir': 'Remove',
    'ayar.listeIndirilmedi': 'Not downloaded yet',
    'ayar.listeHata': 'Update failed: {hata}',
    'ayar.listeDurum': '{n} domains · updated {ne}',
    'ayar.bugun': 'today',
    'ayar.dun': 'yesterday',
    'ayar.gunOnce': '{n} days ago',
    'ayar.bolumIzinler': 'Permission requests',
    'ayar.izinSor': 'Ask every time',
    'ayar.izinVer': 'Always allow',
    'ayar.izinRet': 'Always block',
    'ayar.izinSatir': 'What should happen when a site asks for {izin}?',
    'ayar.bolumGorunum': 'Appearance',
    'ayar.yerImleriCubugu': 'Bookmarks bar',
    'ayar.yerImleriCubuguAciklama': 'Shows bookmarks under the toolbar.',
    'ayar.yenidenBaslat': 'Restart Girginos Browser to apply the language change.',

    'liste.easylist': 'Advertising',
    'liste.easyprivacy': 'Trackers',
    'liste.hataHttps': 'Only https:// addresses can be added.',
    'liste.hataVar': 'This list is already added.',
    /* --- site bilgisi menusu --- */
    'site.baglantiGuvenli': 'Connection is secure',
    'site.baglantiGuvensiz': 'Connection is not secure',
    'site.guvensizUyari': 'Information you enter on this page is sent unencrypted.',
    'site.sertifikaVeren': 'Issued by: {ad}',
    'site.sertifikaSahip': 'Issued to: {ad}',
    'site.sertifikaGecerlilik': 'Valid: {bas} – {bit}',
    'site.parmakIzi': 'Copy fingerprint',
    'site.sertifikaYok': 'No certificate information',
    'site.cerezler': 'Cookies and site data',
    'site.cerezSayisi': '{n} cookies',
    'site.ucuncuTarafCerez': 'Allow third-party cookies',
    'site.veriSil': 'Delete this site’s data',
    'site.engelleyici': 'Tracker blocking',
    'site.izinSifirla': 'Reset permissions for this site',
    'site.ayarlar': 'Site settings',
    /* --- guncelleme --- */
    'menu.guncellemeDenetle': 'Check for updates',
    'ayar.bolumGuncelleme': 'Updates',
    'ayar.surum': 'Version',
    'ayar.guncellemeKontrolEt': 'Check now',
    'ayar.guncellemeIndirDugme': 'Download',
    'ayar.guncellemeKur': 'Restart and install',
    'ayar.guncellemeOtoKontrol': 'Check for updates automatically',
    'ayar.guncellemeOtoKontrolAciklama': 'The signed release information is checked at startup and every 6 hours.',
    'ayar.guncellemeOtoIndir': 'Download automatically',
    'ayar.guncellemeOtoIndirAciklama': 'A new version is downloaded in the background; installing still needs your confirmation.',
    'ayar.guncellemeKanal': 'Update channel',
    'ayar.guncellemeKanalAciklama': 'The beta channel gets new features earlier and is less tested.',
    'ayar.kanalKararli': 'Stable',
    'ayar.kanalBeta': 'Beta',
    'guncelleme.kapali': 'Updates are off: no release key or feed address is configured.',
    'guncelleme.paketlenmemis': 'Running from source; updates only apply to an installed build.',
    'guncelleme.bosta': 'Not checked yet.',
    'guncelleme.kontrol': 'Checking…',
    'guncelleme.guncel': 'You are on the latest version.',
    'guncelleme.bulundu': 'Version {surum} is available.',
    'guncelleme.iniyor': 'Downloading… {n}%',
    'guncelleme.hazir': 'Version {surum} is ready to install.',
    'guncelleme.hata': 'Check failed: {sebep}',
    /* --- yeni sekme ve hata sayfasi --- */
    'sayfa.tekrarDene': 'Try again',
    'sayfa.oneriYenile': 'Reload the page',
    'sayfa.oneriAdres': 'Check the address for typos',
    'sayfa.oneriBaglanti': 'Check your internet connection',
    'sayfa.oneriBilgiGirme': 'Do not enter sensitive information here',
    'hata.dns.baslik': 'Server not found',
    'hata.dns.metin': 'This address could not be resolved to an IP. The domain may be misspelled or offline.',
    'hata.cevrimdisi.baslik': 'No internet connection',
    'hata.cevrimdisi.metin': 'Your device does not appear to be connected to a network.',
    'hata.baglanti.baslik': 'Could not connect',
    'hata.baglanti.metin': 'The server refused the connection, or it was dropped unexpectedly.',
    'hata.zamanAsimi.baslik': 'The connection timed out',
    'hata.zamanAsimi.metin': 'The server did not respond in a reasonable time.',
    'hata.sertifikaAd.baslik': 'Certificate does not match this site',
    'hata.sertifikaAd.metin': 'The domain in the server certificate does not match the address you entered.',
    'hata.sertifikaSure.baslik': 'The certificate has expired',
    'hata.sertifikaSure.metin': 'The server security certificate is no longer valid. Check your device date as well.',
    'hata.sertifikaMakam.baslik': 'The certificate could not be verified',
    'hata.sertifikaMakam.metin': 'The authority that signed the certificate is not recognised. The connection may be intercepted.',
    'hata.cokme.baslik': 'The tab stopped responding',
    'hata.cokme.metin': 'The page closed unexpectedly.',
    'hata.bilinmeyen.baslik': 'This page could not be opened',
    'hata.bilinmeyen.metin': 'Something went wrong while loading the page.',
    'yenisekme.ara': 'Search',
    'yenisekme.sik': 'Frequently visited',
    'yenisekme.oneCikan': 'Featured',
    'yenisekme.kisayolEkle': '+ Add shortcut',
    'yenisekme.kisayolIpucu': 'example.com — press Enter to add',
    'yenisekme.gecersizAdres': 'Enter a valid address',
    'yenisekme.kisayol': 'Shortcut',
    'yenisekme.bosNot': 'The sites you visit most will be listed here as you browse.',
    'yenisekme.engellendi': 'Girginos Browser has blocked {n} tracker requests so far.',
    'yenisekme.engelleyiciAcik': 'Tracker blocking is on. Blocked requests will be counted here.',
    /* --- adres onerileri --- */
    'oneri.ara': 'Search with {motor}',
    'oneri.adreseGit': 'Go to address',
    /* --- gorunum --- */
    'ayar.tema': 'Appearance',
    'ayar.temaAciklama': 'The interface, built-in pages and menus follow this choice.',
    'ayar.temaSistem': 'Match system',
    'ayar.temaAcik': 'Light',
    'ayar.temaKoyu': 'Dark',
    /* --- katman: izin kutusu --- */
    'dialog.izinIstiyor': 'wants to use:',
    'izin.storage-access': 'storage access',
    /* --- site izin duvari --- */
    'panel.siteIzinleri': 'Site permissions',
    'izin.siteYok': 'No permission settings for this page.',
    'izin.durumSor': 'Ask',
    'izin.durumIzin': 'Allow',
    'izin.durumRet': 'Block',
    'izin.varsayilanEk': 'default',
    'izin.siteKarari': 'You set this for this site.',
    'izin.varsayilanIzleniyor': 'Following the global default.',
    'izin.bilinmeyen': 'this permission ({ad})'
  }
};
