'use strict';

module.exports = {
  ad: 'Español',
  yon: 'ltr',
  yerel: 'es-ES',
  metin: {
    'menu.dosya': 'Archivo',
    'menu.yeniSekme': 'Nueva pestaña',
    'menu.sekmeyiKapat': 'Cerrar pestaña',
    'menu.adresCubugu': 'Ir a la barra de direcciones',
    'menu.sayfadaBul': 'Buscar en la página',
    'menu.cikis': 'Salir',
    'menu.duzen': 'Editar',
    'menu.geriAl': 'Deshacer',
    'menu.yinele': 'Rehacer',
    'menu.kes': 'Cortar',
    'menu.kopyala': 'Copiar',
    'menu.yapistir': 'Pegar',
    'menu.tumunuSec': 'Seleccionar todo',
    'menu.gorunum': 'Ver',
    'menu.yenile': 'Recargar',
    'menu.onbelleksizYenile': 'Recargar ignorando la caché',
    'menu.yakinlastir': 'Acercar',
    'menu.uzaklastir': 'Alejar',
    'menu.normalBoyut': 'Tamaño real',
    'menu.tamEkran': 'Pantalla completa',
    'menu.gelistirici': 'Herramientas de desarrollo',
    'menu.arayuzGelistirici': 'Herramientas de desarrollo de la interfaz',
    'menu.gecmis': 'Historial',
    'menu.geri': 'Atrás',
    'menu.ileri': 'Adelante',
    'menu.gecmisiGoster': 'Mostrar historial',
    'menu.indirilenler': 'Descargas',
    'menu.yerImleri': 'Marcadores',
    'menu.yerImiEkle': 'Añadir esta página a marcadores',
    'menu.yerImleriniGoster': 'Mostrar marcadores',
    'menu.yerImleriCubugu': 'Barra de marcadores',
    'menu.sekmeler': 'Pestañas',
    'menu.sonrakiSekme': 'Pestaña siguiente',
    'menu.oncekiSekme': 'Pestaña anterior',
    'menu.nSekme': 'Pestaña {n}',
    'menu.sonSekme': 'Última pestaña',
    'menu.yardim': 'Ayuda',
    'menu.ayarlar': 'Ajustes',
    'menu.hakkinda': 'Acerca de Girginos Browser',
    'hakkinda.detay': 'Un navegador centrado en la privacidad.',
    'menu.yazdir': 'Imprimir…',
    'menu.sayfayiKaydet': 'Guardar página como…',
    'menu.digerAraclar': 'Más herramientas',
    'menu.yakinlastirma': 'Zoom',
    'menu.veriSil': 'Borrar datos de navegación…',
    'arac.onbellek': 'Restablecer la caché',
    'arac.onbellekTemizlendi': 'Caché vaciada, página recargada',
    'arac.onbellekHata': 'No se pudo vaciar la caché',
    'arac.menu': 'Menú',

    'baglam.baglantiYeniSekme': 'Abrir enlace en una pestaña nueva',
    'baglam.baglantiKopyala': 'Copiar dirección del enlace',
    'baglam.gorselYeniSekme': 'Abrir imagen en una pestaña nueva',
    'baglam.gorselKopyala': 'Copiar dirección de la imagen',
    'baglam.gorselKaydet': 'Guardar imagen',
    'baglam.ara': 'Buscar «{q}»',
    'baglam.kaynak': 'Ver código fuente',
    'baglam.incele': 'Inspeccionar elemento',

    'dialog.iptal': 'Cancelar',
    'dialog.ac': 'Abrir',
    'dialog.disBaslik': 'Salir de Girginos Browser',
    'dialog.disMesaj': 'Este enlace «{sema}» se abrirá en otra aplicación.',
    'dialog.reddet': 'Bloquear',
    'dialog.izinVer': 'Permitir',
    'dialog.izinBaslik': 'Solicitud de permiso',
    'dialog.izinMesaj': '{origin} quiere usar:',
    'dialog.izinHatirla': 'Recordar mi decisión para este sitio',
    'dialog.calistirBaslik': 'Este archivo es ejecutable',
    'dialog.calistirMesaj': 'Este archivo podría dañar su equipo.',
    'dialog.calistirDevam': 'Ejecutar de todos modos',
    'dialog.kaynak': 'Origen',

    'izin.notifications': 'notificaciones',
    'izin.geolocation': 'su ubicación',
    'izin.media': 'cámara y micrófono',
    'izin.midi': 'dispositivos MIDI',
    'izin.midiSysex': 'dispositivos MIDI',
    'izin.clipboard-read': 'leer el portapapeles',
    'izin.display-capture': 'compartir pantalla',
    'izin.openExternal': 'abrir otra aplicación',
    'izin.idle-detection': 'detección de inactividad',
    'izin.pointerLock': 'bloquear el puntero',
    'izin.fullscreen': 'pantalla completa',

    'arac.geri': 'Atrás',
    'arac.ileri': 'Adelante',
    'arac.yenile': 'Recargar',
    'arac.durdur': 'Detener',
    'arac.anasayfa': 'Inicio',
    'arac.yeniSekme': 'Nueva pestaña',
    'arac.sekmeyiKapat': 'Cerrar pestaña',
    'arac.gecmis': 'Historial',
    'arac.indirilenler': 'Descargas',
    'arac.ayarlar': 'Ajustes',
    'arac.adresIpucu': 'Busca o escribe una dirección',
    'arac.yerImiEkle': 'Añadir marcador',
    'arac.yerImiCikar': 'Quitar marcador',
    'arac.kalkanAcik': '{n} rastreadores bloqueados — pulsa para desactivar',
    'arac.kalkanKapali': 'Bloqueo desactivado en este sitio — pulsa para activar',
    'arac.guvenli': 'Conexión cifrada (HTTPS)',
    'arac.guvensiz': 'Conexión sin cifrar',
    'arac.yeniSekmeBaslik': 'Nueva pestaña',
    'arac.adsiz': 'Sin título',

    'bul.ipucu': 'Buscar en la página',
    'bul.onceki': 'Anterior',
    'bul.sonraki': 'Siguiente',
    'bul.kapat': 'Cerrar',

    'panel.gecmis': 'Historial',
    'panel.yerImleri': 'Marcadores',
    'panel.indirilenler': 'Descargas',
    'panel.ayarlar': 'Ajustes',
    'panel.kapat': 'Cerrar panel',
    'panel.kaldir': 'Quitar',
    'gecmis.ara': 'Buscar en el historial',
    'gecmis.temizle': 'Borrar historial',
    'gecmis.bos': 'Tu historial está vacío.',
    'gecmis.eslesmeYok': 'No hay entradas que coincidan.',
    'gecmis.bugun': 'Hoy',
    'gecmis.dun': 'Ayer',
    'yerimi.bos': 'Todavía no tienes marcadores.',
    'yerimi.cubukBos': 'Sin marcadores — pulsa Ctrl+D para añadir esta página',
    'yerimi.tumu': 'Todos los marcadores',
    'yerimi.ac': 'Abrir',
    'yerimi.yeniSekmedeAc': 'Abrir en una pestaña nueva',
    'yerimi.adresiKopyala': 'Copiar dirección',
    'yerimi.duzenle': 'Cambiar nombre…',
    'yerimi.cubuguGizle': 'Ocultar la barra de marcadores',

    'indirme.bos': 'Aún no hay descargas.',
    'indirme.devam': 'Descargando',
    'indirme.tamam': 'Completada',
    'indirme.iptal': 'Cancelada',
    'indirme.hata': 'Fallida',
    'indirme.kesildi': 'Interrumpida',
    'indirme.ac': 'Abrir',
    'indirme.klasor': 'Mostrar en la carpeta',
    'indirme.tumunuGoster': 'Ver todas',

    'ayar.engellenenSayi': 'Rastreadores bloqueados hasta ahora',
    'ayar.yukluAlan': 'Dominios cargados de las listas',
    'ayar.yerImiSayi': 'Marcadores',
    'ayar.bolumArama': 'Búsqueda e inicio',
    'ayar.dil': 'Idioma',
    'ayar.dilAciklama': 'Los menús, paneles y páginas de error usan este idioma.',
    'ayar.dilSistem': 'Idioma del sistema',
    'ayar.aramaMotoru': 'Motor de búsqueda',
    'ayar.aramaMotoruAciklama': 'Las búsquedas escritas en la barra de direcciones van aquí.',
    'ayar.anasayfa': 'Página de inicio',
    'ayar.anasayfaAciklama': 'La dirección que abre el botón de inicio.',
    'ayar.anasayfaIpucu': 'Déjalo vacío para la página de nueva pestaña',
    'ayar.bolumGizlilik': 'Privacidad',
    'ayar.engelleyici': 'Bloqueador de rastreadores y anuncios',
    'ayar.engelleyiciAciklama': 'Cancela las peticiones a dominios de publicidad y rastreo conocidos.',
    'ayar.dnt': 'Enviar señal de no rastrear',
    'ayar.dntAciklama': 'Añade las cabeceras DNT y Sec-GPC a cada petición.',
    'ayar.ucuncuTarafCerez': 'Bloquear cookies de terceros',
    'ayar.ucuncuTarafCerezAciklama': 'El principal vehículo del rastreo entre sitios. Si un sitio deja de funcionar, puedes permitirlo desde el menú del candado en la barra de direcciones. El cambio surte pleno efecto tras reiniciar.',
    'ayar.kapanistaCerezSil': 'Eliminar las cookies al salir',
    'ayar.kapanistaCerezSilAciklama': 'Se conservan las cookies de los sitios de tus marcadores, así sigues con la sesión iniciada.',
    'ayar.gecmisiKaydet': 'Guardar historial',
    'ayar.gecmisiKaydetAciklama': 'Si está desactivado, las páginas visitadas nunca se escriben en disco.',
    'ayar.cerezler': 'Cookies y caché',
    'ayar.cerezlerAciklama': 'Borra las cookies, el almacenamiento local y la caché de todos los sitios.',
    'ayar.veriTemizle': 'Borrar datos',
    'ayar.temizleniyor': 'Borrando…',
    'ayar.temizlendi': 'Borrado',
    'ayar.siteIzinleri': 'Permisos de sitios',
    'ayar.siteIzinleriAciklama': 'Borra las decisiones recordadas de ubicación, cámara y notificaciones, y las excepciones del bloqueador.',
    'ayar.izinSifirla': 'Restablecer permisos',
    'ayar.sifirlandi': 'Restablecido',
    'ayar.bolumVekil': 'Proxy',
    'ayar.vekil': 'Servidor proxy',
    'ayar.vekilAciklama': 'Todo pasa por el proxy: la navegación, las listas de filtros y las actualizaciones. Con un proxy activo, WebRTC no puede revelar tu dirección real.',
    'ayar.vekilKapali': 'Desactivado',
    'ayar.vekilSistem': 'Configuración del sistema',
    'ayar.vekilElle': 'Manual',
    'ayar.vekilAdres': 'Dirección',
    'ayar.vekilAdresAciklama': 'Por ejemplo socks5://127.0.0.1:9050 (Tor) o http://192.168.1.10:8080',
    'ayar.vekilAdresHatali': 'Esa dirección no se aceptó y no se ha guardado. Formato: socks5://servidor:puerto',
    'ayar.vekilReddedildi': 'El navegador no aceptó la regla del proxy, así que las conexiones apuntan a un proxy inalcanzable. Revisa la dirección.',
    'ayar.vekilAtlaHatali': 'Algunas entradas no se aceptaron. Cada una debe ser un dominio, *.ejemplo.com o 10.0.0.0/8.',
    'ayar.vekilAtla': 'Sitios que omiten el proxy',
    'ayar.vekilAtlaAciklama': 'Estos dominios se conectan directamente. Las direcciones locales siempre quedan excluidas.',
    'ayar.bolumListeler': 'Listas de filtros',
    'ayar.listeKullan': 'Usar listas descargadas',
    'ayar.listeKullanAciklama': 'También se bloquean los dominios de listas como EasyList. Si está desactivado, solo se aplica la lista integrada.',
    'ayar.otomatikGuncelle': 'Actualizar automáticamente',
    'ayar.otomatikGuncelleAciklama': 'Las listas se renuevan en segundo plano con el intervalo que indican (normalmente cada 4 días).',
    'ayar.listeYenile': 'Renovar listas',
    'ayar.listeYenileAciklama': 'Las descarga todas de nuevo ahora mismo.',
    'ayar.simdiGuncelle': 'Actualizar ahora',
    'ayar.guncelleniyor': 'Actualizando…',
    'ayar.listeEkle': 'Añade tu propia lista',
    'ayar.listeEkleAciklama': 'Una dirección https en formato Adblock Plus, hosts o dominio simple.',
    'ayar.listeEkleIpucu': 'https://... dirección de la lista',
    'ayar.ekle': 'Añadir',
    'ayar.ekleniyor': 'Añadiendo…',
    'ayar.listeKaldir': 'Quitar',
    'ayar.listeIndirilmedi': 'Aún no descargada',
    'ayar.listeHata': 'No se pudo actualizar: {hata}',
    'ayar.listeDurum': '{n} dominios · actualizada {ne}',
    'ayar.bugun': 'hoy',
    'ayar.dun': 'ayer',
    'ayar.gunOnce': 'hace {n} días',
    'ayar.bolumIzinler': 'Solicitudes de permiso',
    'ayar.izinSor': 'Preguntar siempre',
    'ayar.izinVer': 'Permitir siempre',
    'ayar.izinRet': 'Bloquear siempre',
    'ayar.izinSatir': '¿Qué hacer cuando un sitio pide {izin}?',
    'ayar.bolumGorunum': 'Apariencia',
    'ayar.yerImleriCubugu': 'Barra de marcadores',
    'ayar.yerImleriCubuguAciklama': 'Muestra los marcadores bajo la barra de herramientas.',
    'ayar.yenidenBaslat': 'Reinicia Girginos Browser para aplicar el idioma.',

    'liste.easylist': 'Publicidad',
    'liste.easyprivacy': 'Rastreadores',
    'liste.hataHttps': 'Solo se pueden añadir direcciones https://.',
    'liste.hataVar': 'Esta lista ya está añadida.',
    /* --- site bilgisi menusu --- */
    'site.baglantiGuvenli': 'La conexión es segura',
    'site.baglantiGuvensiz': 'La conexión no es segura',
    'site.guvensizUyari': 'La información que introduzcas en esta página se envía sin cifrar.',
    'site.sertifikaVeren': 'Emitido por: {ad}',
    'site.sertifikaSahip': 'Emitido para: {ad}',
    'site.sertifikaGecerlilik': 'Validez: {bas} – {bit}',
    'site.parmakIzi': 'Copiar huella digital',
    'site.sertifikaYok': 'Sin información del certificado',
    'site.cerezler': 'Cookies y datos del sitio',
    'site.cerezSayisi': '{n} cookies',
    'site.ucuncuTarafCerez': 'Permitir cookies de terceros',
    'site.veriSil': 'Eliminar los datos de este sitio',
    'site.engelleyici': 'Bloqueo de rastreadores',
    'site.izinSifirla': 'Restablecer permisos de este sitio',
    'site.ayarlar': 'Configuración del sitio',
    /* --- guncelleme --- */
    'menu.guncellemeDenetle': 'Buscar actualizaciones',
    'ayar.bolumGuncelleme': 'Actualizaciones',
    'ayar.surum': 'Versión',
    'ayar.guncellemeKontrolEt': 'Comprobar ahora',
    'ayar.guncellemeIndirDugme': 'Descargar',
    'ayar.guncellemeKur': 'Reiniciar e instalar',
    'ayar.guncellemeOtoKontrol': 'Buscar actualizaciones automáticamente',
    'ayar.guncellemeOtoKontrolAciklama': 'La información de versión firmada se comprueba al inicio y cada 6 horas.',
    'ayar.guncellemeOtoIndir': 'Descargar automáticamente',
    'ayar.guncellemeOtoIndirAciklama': 'La nueva versión se descarga en segundo plano; la instalación sigue requiriendo tu confirmación.',
    'ayar.guncellemeKanal': 'Canal de actualización',
    'ayar.guncellemeKanalAciklama': 'El canal beta recibe novedades antes y está menos probado.',
    'ayar.kanalKararli': 'Estable',
    'ayar.kanalBeta': 'Beta',
    'guncelleme.kapali': 'Actualizaciones desactivadas: no hay clave de publicación ni dirección configurada.',
    'guncelleme.paketlenmemis': 'Ejecutándose desde el código fuente; las actualizaciones solo se aplican a una versión instalada.',
    'guncelleme.bosta': 'Aún no comprobado.',
    'guncelleme.kontrol': 'Comprobando…',
    'guncelleme.guncel': 'Estás en la última versión.',
    'guncelleme.bulundu': 'La versión {surum} está disponible.',
    'guncelleme.iniyor': 'Descargando… {n} %',
    'guncelleme.hazir': 'La versión {surum} está lista para instalar.',
    'guncelleme.hata': 'No se pudo comprobar: {sebep}',
    /* --- yeni sekme ve hata sayfasi --- */
    'sayfa.tekrarDene': 'Reintentar',
    'sayfa.oneriYenile': 'Recarga la página',
    'sayfa.oneriAdres': 'Comprueba si la dirección tiene erratas',
    'sayfa.oneriBaglanti': 'Comprueba tu conexión a internet',
    'sayfa.oneriBilgiGirme': 'No introduzcas información sensible aquí',
    'hata.dns.baslik': 'Servidor no encontrado',
    'hata.dns.metin': 'No se pudo resolver la IP de esta dirección. El dominio puede estar mal escrito o fuera de línea.',
    'hata.cevrimdisi.baslik': 'Sin conexión a internet',
    'hata.cevrimdisi.metin': 'Tu dispositivo no parece estar conectado a una red.',
    'hata.baglanti.baslik': 'No se pudo conectar',
    'hata.baglanti.metin': 'El servidor rechazó la conexión o esta se interrumpió inesperadamente.',
    'hata.zamanAsimi.baslik': 'Se agotó el tiempo de conexión',
    'hata.zamanAsimi.metin': 'El servidor no respondió en un tiempo razonable.',
    'hata.sertifikaAd.baslik': 'El certificado no corresponde a este sitio',
    'hata.sertifikaAd.metin': 'El dominio del certificado no coincide con la dirección que has introducido.',
    'hata.sertifikaSure.baslik': 'El certificado ha caducado',
    'hata.sertifikaSure.metin': 'El certificado de seguridad del servidor ya no es válido. Comprueba también la fecha del dispositivo.',
    'hata.sertifikaMakam.baslik': 'No se pudo verificar el certificado',
    'hata.sertifikaMakam.metin': 'La autoridad que firmó el certificado no es reconocida. La conexión podría estar interceptada.',
    'hata.cokme.baslik': 'La pestaña dejó de responder',
    'hata.cokme.metin': 'La página se cerró de forma inesperada.',
    'hata.bilinmeyen.baslik': 'No se pudo abrir esta página',
    'hata.bilinmeyen.metin': 'Ocurrió un problema desconocido al cargar la página.',
    'yenisekme.ara': 'Buscar',
    'yenisekme.sik': 'Sitios frecuentes',
    'yenisekme.oneCikan': 'Destacado',
    'yenisekme.kisayolEkle': '+ Añadir acceso directo',
    'yenisekme.kisayolIpucu': 'ejemplo.com — pulsa Enter para añadir',
    'yenisekme.gecersizAdres': 'Escribe una dirección válida',
    'yenisekme.kisayol': 'Acceso directo',
    'yenisekme.bosNot': 'Los sitios que más visitas aparecerán aquí.',
    'yenisekme.engellendi': 'Girginos Browser ha bloqueado {n} peticiones de rastreadores hasta ahora.',
    'yenisekme.engelleyiciAcik': 'El bloqueo de rastreadores está activo. Las peticiones bloqueadas se contarán aquí.',
    /* --- adres onerileri --- */
    'oneri.ara': 'Buscar con {motor}',
    'oneri.adreseGit': 'Ir a la dirección',
    /* --- gorunum --- */
    'ayar.tema': 'Apariencia',
    'ayar.temaAciklama': 'La interfaz, las páginas internas y los menús siguen esta opción.',
    'ayar.temaSistem': 'Igual que el sistema',
    'ayar.temaAcik': 'Claro',
    'ayar.temaKoyu': 'Oscuro',
    /* --- katman: izin kutusu --- */
    'dialog.izinIstiyor': 'solicita:',
    'izin.storage-access': 'acceso al almacenamiento',
    /* --- site izin duvari --- */
    'panel.siteIzinleri': 'Permisos del sitio',
    'izin.siteYok': 'No hay permisos para esta página.',
    'izin.durumSor': 'Preguntar',
    'izin.durumIzin': 'Permitir',
    'izin.durumRet': 'Bloquear',
    'izin.varsayilanEk': 'predeterminado',
    'izin.siteKarari': 'Lo estableciste para este sitio.',
    'izin.varsayilanIzleniyor': 'Se aplica el valor predeterminado.',
    'izin.bilinmeyen': 'este permiso ({ad})'
  }
};
