'use strict';

module.exports = {
  ad: 'Français',
  yon: 'ltr',
  yerel: 'fr-FR',
  metin: {
    'menu.dosya': 'Fichier',
    'menu.yeniSekme': 'Nouvel onglet',
    'menu.sekmeyiKapat': 'Fermer l’onglet',
    'menu.adresCubugu': 'Aller à la barre d’adresse',
    'menu.sayfadaBul': 'Rechercher dans la page',
    'menu.cikis': 'Quitter',
    'menu.duzen': 'Édition',
    'menu.geriAl': 'Annuler',
    'menu.yinele': 'Rétablir',
    'menu.kes': 'Couper',
    'menu.kopyala': 'Copier',
    'menu.yapistir': 'Coller',
    'menu.tumunuSec': 'Tout sélectionner',
    'menu.gorunum': 'Affichage',
    'menu.yenile': 'Actualiser',
    'menu.onbelleksizYenile': 'Actualiser en ignorant le cache',
    'menu.yakinlastir': 'Zoom avant',
    'menu.uzaklastir': 'Zoom arrière',
    'menu.normalBoyut': 'Taille réelle',
    'menu.tamEkran': 'Plein écran',
    'menu.gelistirici': 'Outils de développement',
    'menu.arayuzGelistirici': 'Outils de développement de l’interface',
    'menu.gecmis': 'Historique',
    'menu.geri': 'Précédent',
    'menu.ileri': 'Suivant',
    'menu.gecmisiGoster': 'Afficher l’historique',
    'menu.indirilenler': 'Téléchargements',
    'menu.yerImleri': 'Marque-pages',
    'menu.yerImiEkle': 'Ajouter cette page aux marque-pages',
    'menu.yerImleriniGoster': 'Afficher les marque-pages',
    'menu.yerImleriCubugu': 'Barre des marque-pages',
    'menu.sekmeler': 'Onglets',
    'menu.sonrakiSekme': 'Onglet suivant',
    'menu.oncekiSekme': 'Onglet précédent',
    'menu.nSekme': 'Onglet {n}',
    'menu.sonSekme': 'Dernier onglet',
    'menu.yardim': 'Aide',
    'menu.ayarlar': 'Paramètres',
    'menu.hakkinda': 'À propos de Girginos Browser',
    'hakkinda.detay': 'Un navigateur axé sur la confidentialité.',
    'menu.yazdir': 'Imprimer…',
    'menu.sayfayiKaydet': 'Enregistrer la page sous…',
    'menu.digerAraclar': 'Plus d’outils',
    'menu.yakinlastirma': 'Zoom',
    'menu.veriSil': 'Effacer les données de navigation…',
    'arac.onbellek': 'Réinitialiser le cache',
    'arac.onbellekTemizlendi': 'Cache vidé, page rechargée',
    'arac.onbellekHata': 'Impossible de vider le cache',
    'arac.menu': 'Menu',

    'baglam.baglantiYeniSekme': 'Ouvrir le lien dans un nouvel onglet',
    'baglam.baglantiKopyala': 'Copier l’adresse du lien',
    'baglam.gorselYeniSekme': 'Ouvrir l’image dans un nouvel onglet',
    'baglam.gorselKopyala': 'Copier l’adresse de l’image',
    'baglam.gorselKaydet': 'Enregistrer l’image',
    'baglam.ara': 'Rechercher « {q} »',
    'baglam.kaynak': 'Afficher le code source',
    'baglam.incele': 'Inspecter l’élément',

    'dialog.iptal': 'Annuler',
    'dialog.ac': 'Ouvrir',
    'dialog.disBaslik': 'Quitter Girginos Browser',
    'dialog.disMesaj': 'Ce lien « {sema} » s’ouvrira dans une autre application.',
    'dialog.reddet': 'Bloquer',
    'dialog.izinVer': 'Autoriser',
    'dialog.izinBaslik': 'Demande d’autorisation',
    'dialog.izinMesaj': '{origin} souhaite utiliser :',
    'dialog.izinHatirla': 'Mémoriser mon choix pour ce site',
    'dialog.calistirBaslik': 'Ce fichier est exécutable',
    'dialog.calistirMesaj': 'Ce fichier pourrait endommager votre ordinateur.',
    'dialog.calistirDevam': 'Exécuter quand même',
    'dialog.kaynak': 'Source',

    'izin.notifications': 'les notifications',
    'izin.geolocation': 'votre position',
    'izin.media': 'la caméra et le microphone',
    'izin.midi': 'les appareils MIDI',
    'izin.midiSysex': 'les appareils MIDI',
    'izin.clipboard-read': 'la lecture du presse-papiers',
    'izin.display-capture': 'le partage d’écran',
    'izin.openExternal': 'l’ouverture d’une autre application',
    'izin.idle-detection': 'la détection d’inactivité',
    'izin.pointerLock': 'le verrouillage du pointeur',
    'izin.fullscreen': 'le plein écran',

    'arac.geri': 'Précédent',
    'arac.ileri': 'Suivant',
    'arac.yenile': 'Actualiser',
    'arac.durdur': 'Arrêter',
    'arac.anasayfa': 'Accueil',
    'arac.yeniSekme': 'Nouvel onglet',
    'arac.sekmeyiKapat': 'Fermer l’onglet',
    'arac.gecmis': 'Historique',
    'arac.indirilenler': 'Téléchargements',
    'arac.ayarlar': 'Paramètres',
    'arac.adresIpucu': 'Rechercher ou saisir une adresse',
    'arac.yerImiEkle': 'Ajouter un marque-page',
    'arac.yerImiCikar': 'Retirer le marque-page',
    'arac.kalkanAcik': '{n} traqueurs bloqués — cliquez pour désactiver',
    'arac.kalkanKapali': 'Blocage désactivé sur ce site — cliquez pour activer',
    'arac.guvenli': 'Connexion chiffrée (HTTPS)',
    'arac.guvensiz': 'Connexion non chiffrée',
    'arac.yeniSekmeBaslik': 'Nouvel onglet',
    'arac.adsiz': 'Sans titre',

    'bul.ipucu': 'Rechercher dans la page',
    'bul.onceki': 'Précédent',
    'bul.sonraki': 'Suivant',
    'bul.kapat': 'Fermer',

    'panel.gecmis': 'Historique',
    'panel.yerImleri': 'Marque-pages',
    'panel.indirilenler': 'Téléchargements',
    'panel.ayarlar': 'Paramètres',
    'panel.kapat': 'Fermer le panneau',
    'panel.kaldir': 'Retirer',
    'gecmis.ara': 'Rechercher dans l’historique',
    'gecmis.temizle': 'Effacer l’historique',
    'gecmis.bos': 'Votre historique est vide.',
    'gecmis.eslesmeYok': 'Aucune entrée correspondante.',
    'gecmis.bugun': 'Aujourd’hui',
    'gecmis.dun': 'Hier',
    'yerimi.bos': 'Vous n’avez pas encore de marque-pages.',
    'yerimi.cubukBos': 'Aucun marque-page — Ctrl+D pour ajouter cette page',
    'yerimi.tumu': 'Tous les marque-pages',
    'yerimi.ac': 'Ouvrir',
    'yerimi.yeniSekmedeAc': 'Ouvrir dans un nouvel onglet',
    'yerimi.adresiKopyala': 'Copier l’adresse',
    'yerimi.duzenle': 'Renommer…',
    'yerimi.cubuguGizle': 'Masquer la barre des marque-pages',

    'indirme.bos': 'Aucun téléchargement pour l’instant.',
    'indirme.devam': 'Téléchargement',
    'indirme.tamam': 'Terminé',
    'indirme.iptal': 'Annulé',
    'indirme.hata': 'Échec',
    'indirme.kesildi': 'Interrompu',
    'indirme.ac': 'Ouvrir',
    'indirme.klasor': 'Afficher dans le dossier',
    'indirme.tumunuGoster': 'Tout afficher',

    'ayar.engellenenSayi': 'Traqueurs bloqués jusqu’ici',
    'ayar.yukluAlan': 'Domaines chargés depuis les listes',
    'ayar.yerImiSayi': 'Marque-pages',
    'ayar.bolumArama': 'Recherche et démarrage',
    'ayar.dil': 'Langue',
    'ayar.dilAciklama': 'Les menus, panneaux et pages d’erreur utilisent cette langue.',
    'ayar.dilSistem': 'Langue du système',
    'ayar.aramaMotoru': 'Moteur de recherche',
    'ayar.aramaMotoruAciklama': 'Les recherches saisies dans la barre d’adresse vont ici.',
    'ayar.anasayfa': 'Page d’accueil',
    'ayar.anasayfaAciklama': 'L’adresse ouverte par le bouton d’accueil.',
    'ayar.anasayfaIpucu': 'Laissez vide pour la page nouvel onglet',
    'ayar.bolumGizlilik': 'Confidentialité',
    'ayar.engelleyici': 'Bloqueur de traqueurs et de publicités',
    'ayar.engelleyiciAciklama': 'Annule les requêtes vers les domaines publicitaires et de suivi connus.',
    'ayar.dnt': 'Envoyer le signal de non-suivi',
    'ayar.dntAciklama': 'Ajoute les en-têtes DNT et Sec-GPC à chaque requête.',
    'ayar.ucuncuTarafCerez': 'Bloquer les cookies tiers',
    'ayar.ucuncuTarafCerezAciklama': 'Le principal vecteur du suivi entre sites. Si un site ne fonctionne plus, vous pouvez l’autoriser depuis le menu du cadenas dans la barre d’adresse. La modification prend pleinement effet après un redémarrage.',
    'ayar.kapanistaCerezSil': 'Supprimer les cookies à la fermeture',
    'ayar.kapanistaCerezSilAciklama': 'Les cookies des sites de vos favoris sont conservés, vous y restez connecté.',
    'ayar.gecmisiKaydet': 'Enregistrer l’historique',
    'ayar.gecmisiKaydetAciklama': 'Désactivé, les pages visitées ne sont jamais écrites sur le disque.',
    'ayar.cerezler': 'Cookies et cache',
    'ayar.cerezlerAciklama': 'Supprime les cookies, le stockage local et le cache de tous les sites.',
    'ayar.veriTemizle': 'Effacer les données',
    'ayar.temizleniyor': 'Effacement…',
    'ayar.temizlendi': 'Effacé',
    'ayar.siteIzinleri': 'Autorisations des sites',
    'ayar.siteIzinleriAciklama': 'Supprime les choix mémorisés (position, caméra, notifications) et les exceptions du bloqueur.',
    'ayar.izinSifirla': 'Réinitialiser les autorisations',
    'ayar.sifirlandi': 'Réinitialisé',
    'ayar.bolumVekil': 'Proxy',
    'ayar.vekil': 'Serveur proxy',
    'ayar.vekilAciklama': 'Tout passe par le proxy : la navigation, les listes de filtres et les mises à jour. Tant qu’un proxy est actif, WebRTC ne peut pas révéler votre adresse réelle.',
    'ayar.vekilKapali': 'Désactivé',
    'ayar.vekilSistem': 'Réglage du système',
    'ayar.vekilElle': 'Manuel',
    'ayar.vekilAdres': 'Adresse',
    'ayar.vekilAdresAciklama': 'Par exemple socks5://127.0.0.1:9050 (Tor) ou http://192.168.1.10:8080',
    'ayar.vekilAdresHatali': 'Cette adresse a été refusée et n’a pas été enregistrée. Format : socks5://hôte:port',
    'ayar.vekilReddedildi': 'Le navigateur n’a pas accepté la règle de proxy ; les connexions pointent vers un proxy injoignable. Vérifiez l’adresse.',
    'ayar.vekilAtlaHatali': 'Certaines entrées ont été refusées. Chacune doit être un domaine, *.exemple.com ou 10.0.0.0/8.',
    'ayar.vekilAtla': 'Sites sans proxy',
    'ayar.vekilAtlaAciklama': 'Ces domaines se connectent directement. Les adresses locales sont toujours exclues.',
    'ayar.bolumListeler': 'Listes de filtres',
    'ayar.listeKullan': 'Utiliser les listes téléchargées',
    'ayar.listeKullanAciklama': 'Les domaines de listes comme EasyList sont aussi bloqués. Désactivé, seule la liste intégrée s’applique.',
    'ayar.otomatikGuncelle': 'Mettre à jour automatiquement',
    'ayar.otomatikGuncelleAciklama': 'Les listes se rafraîchissent en arrière-plan selon leur intervalle (souvent tous les 4 jours).',
    'ayar.listeYenile': 'Rafraîchir les listes',
    'ayar.listeYenileAciklama': 'Les télécharge toutes à nouveau immédiatement.',
    'ayar.simdiGuncelle': 'Mettre à jour',
    'ayar.guncelleniyor': 'Mise à jour…',
    'ayar.listeEkle': 'Ajouter votre liste',
    'ayar.listeEkleAciklama': 'Une adresse https au format Adblock Plus, hosts ou domaine simple.',
    'ayar.listeEkleIpucu': 'https://... adresse de la liste',
    'ayar.ekle': 'Ajouter',
    'ayar.ekleniyor': 'Ajout…',
    'ayar.listeKaldir': 'Retirer',
    'ayar.listeIndirilmedi': 'Pas encore téléchargée',
    'ayar.listeHata': 'Échec de la mise à jour : {hata}',
    'ayar.listeDurum': '{n} domaines · mise à jour {ne}',
    'ayar.bugun': 'aujourd’hui',
    'ayar.dun': 'hier',
    'ayar.gunOnce': 'il y a {n} jours',
    'ayar.bolumIzinler': 'Demandes d’autorisation',
    'ayar.izinSor': 'Demander à chaque fois',
    'ayar.izinVer': 'Toujours autoriser',
    'ayar.izinRet': 'Toujours bloquer',
    'ayar.izinSatir': 'Que faire lorsqu’un site demande {izin} ?',
    'ayar.bolumGorunum': 'Apparence',
    'ayar.yerImleriCubugu': 'Barre des marque-pages',
    'ayar.yerImleriCubuguAciklama': 'Affiche les marque-pages sous la barre d’outils.',
    'ayar.yenidenBaslat': 'Redémarrez Girginos Browser pour appliquer la langue.',

    'liste.easylist': 'Publicité',
    'liste.easyprivacy': 'Traqueurs',
    'liste.hataHttps': 'Seules les adresses https:// peuvent être ajoutées.',
    'liste.hataVar': 'Cette liste est déjà ajoutée.',
    /* --- site bilgisi menusu --- */
    'site.baglantiGuvenli': 'Connexion sécurisée',
    'site.baglantiGuvensiz': 'Connexion non sécurisée',
    'site.guvensizUyari': 'Les informations saisies sur cette page sont envoyées sans chiffrement.',
    'site.sertifikaVeren': 'Émis par : {ad}',
    'site.sertifikaSahip': 'Émis pour : {ad}',
    'site.sertifikaGecerlilik': 'Validité : {bas} – {bit}',
    'site.parmakIzi': 'Copier l’empreinte',
    'site.sertifikaYok': 'Aucune information de certificat',
    'site.cerezler': 'Cookies et données de site',
    'site.cerezSayisi': '{n} cookies',
    'site.ucuncuTarafCerez': 'Autoriser les cookies tiers',
    'site.veriSil': 'Supprimer les données de ce site',
    'site.engelleyici': 'Blocage des traqueurs',
    'site.izinSifirla': 'Réinitialiser les autorisations de ce site',
    'site.ayarlar': 'Paramètres du site',
    /* --- guncelleme --- */
    'menu.guncellemeDenetle': 'Rechercher des mises à jour',
    'ayar.bolumGuncelleme': 'Mises à jour',
    'ayar.surum': 'Version',
    'ayar.guncellemeKontrolEt': 'Vérifier maintenant',
    'ayar.guncellemeIndirDugme': 'Télécharger',
    'ayar.guncellemeKur': 'Redémarrer et installer',
    'ayar.guncellemeOtoKontrol': 'Rechercher automatiquement les mises à jour',
    'ayar.guncellemeOtoKontrolAciklama': 'Les informations de version signées sont vérifiées au démarrage et toutes les 6 heures.',
    'ayar.guncellemeOtoIndir': 'Télécharger automatiquement',
    'ayar.guncellemeOtoIndirAciklama': 'La nouvelle version est téléchargée en arrière-plan ; l’installation demande toujours votre accord.',
    'ayar.guncellemeKanal': 'Canal de mise à jour',
    'ayar.guncellemeKanalAciklama': 'Le canal bêta reçoit les nouveautés plus tôt et est moins testé.',
    'ayar.kanalKararli': 'Stable',
    'ayar.kanalBeta': 'Bêta',
    'guncelleme.kapali': 'Mises à jour désactivées : aucune clé de publication ni adresse de flux configurée.',
    'guncelleme.paketlenmemis': 'Exécution depuis les sources ; les mises à jour ne s’appliquent qu’à une version installée.',
    'guncelleme.bosta': 'Pas encore vérifié.',
    'guncelleme.kontrol': 'Vérification…',
    'guncelleme.guncel': 'Vous utilisez la dernière version.',
    'guncelleme.bulundu': 'La version {surum} est disponible.',
    'guncelleme.iniyor': 'Téléchargement… {n} %',
    'guncelleme.hazir': 'La version {surum} est prête à installer.',
    'guncelleme.hata': 'Échec de la vérification : {sebep}',
    /* --- yeni sekme ve hata sayfasi --- */
    'sayfa.tekrarDene': 'Réessayer',
    'sayfa.oneriYenile': 'Actualisez la page',
    'sayfa.oneriAdres': 'Vérifiez l’adresse (faute de frappe)',
    'sayfa.oneriBaglanti': 'Vérifiez votre connexion internet',
    'sayfa.oneriBilgiGirme': 'N’entrez pas d’informations sensibles ici',
    'hata.dns.baslik': 'Serveur introuvable',
    'hata.dns.metin': 'Cette adresse n’a pas pu être résolue en IP. Le domaine est peut-être mal écrit ou hors ligne.',
    'hata.cevrimdisi.baslik': 'Pas de connexion internet',
    'hata.cevrimdisi.metin': 'Votre appareil ne semble pas connecté à un réseau.',
    'hata.baglanti.baslik': 'Connexion impossible',
    'hata.baglanti.metin': 'Le serveur a refusé la connexion, ou celle-ci a été interrompue.',
    'hata.zamanAsimi.baslik': 'Délai de connexion dépassé',
    'hata.zamanAsimi.metin': 'Le serveur n’a pas répondu dans un délai raisonnable.',
    'hata.sertifikaAd.baslik': 'Le certificat ne correspond pas à ce site',
    'hata.sertifikaAd.metin': 'Le domaine du certificat ne correspond pas à l’adresse saisie.',
    'hata.sertifikaSure.baslik': 'Le certificat a expiré',
    'hata.sertifikaSure.metin': 'Le certificat de sécurité du serveur n’est plus valide. Vérifiez aussi la date de votre appareil.',
    'hata.sertifikaMakam.baslik': 'Le certificat n’a pas pu être vérifié',
    'hata.sertifikaMakam.metin': 'L’autorité ayant signé le certificat n’est pas reconnue. La connexion peut être interceptée.',
    'hata.cokme.baslik': 'L’onglet ne répond plus',
    'hata.cokme.metin': 'La page s’est fermée de façon inattendue.',
    'hata.bilinmeyen.baslik': 'Cette page n’a pas pu être ouverte',
    'hata.bilinmeyen.metin': 'Un problème inconnu est survenu lors du chargement.',
    'yenisekme.ara': 'Rechercher',
    'yenisekme.sik': 'Sites fréquents',
    'yenisekme.oneCikan': 'À la une',
    'yenisekme.kisayolEkle': '+ Ajouter un raccourci',
    'yenisekme.kisayolIpucu': 'exemple.fr — Entrée pour ajouter',
    'yenisekme.gecersizAdres': 'Saisissez une adresse valide',
    'yenisekme.kisayol': 'Raccourci',
    'yenisekme.bosNot': 'Les sites que vous visitez le plus apparaîtront ici.',
    'yenisekme.engellendi': 'Girginos Browser a bloqué {n} requêtes de traqueurs jusqu’ici.',
    'yenisekme.engelleyiciAcik': 'Le blocage des traqueurs est actif. Les requêtes bloquées seront comptées ici.',
    /* --- adres onerileri --- */
    'oneri.ara': 'Rechercher avec {motor}',
    'oneri.adreseGit': 'Ouvrir l’adresse',
    /* --- gorunum --- */
    'ayar.tema': 'Apparence',
    'ayar.temaAciklama': 'L’interface, les pages internes et les menus suivent ce choix.',
    'ayar.temaSistem': 'Comme le système',
    'ayar.temaAcik': 'Clair',
    'ayar.temaKoyu': 'Sombre',
    /* --- katman: izin kutusu --- */
    'dialog.izinIstiyor': 'demande :',
    'izin.storage-access': 'accès au stockage',
    /* --- site izin duvari --- */
    'panel.siteIzinleri': 'Autorisations du site',
    'izin.siteYok': 'Aucune autorisation pour cette page.',
    'izin.durumSor': 'Demander',
    'izin.durumIzin': 'Autoriser',
    'izin.durumRet': 'Bloquer',
    'izin.varsayilanEk': 'par défaut',
    'izin.siteKarari': 'Vous l’avez défini pour ce site.',
    'izin.varsayilanIzleniyor': 'Valeur par défaut appliquée.',
    'izin.bilinmeyen': 'cette autorisation ({ad})'
  }
};
