'use strict';

module.exports = {
  ad: 'Italiano',
  yon: 'ltr',
  yerel: 'it-IT',
  metin: {
    'menu.dosya': 'File',
    'menu.yeniSekme': 'Nuova scheda',
    'menu.sekmeyiKapat': 'Chiudi scheda',
    'menu.adresCubugu': 'Vai alla barra degli indirizzi',
    'menu.sayfadaBul': 'Trova nella pagina',
    'menu.cikis': 'Esci',
    'menu.duzen': 'Modifica',
    'menu.geriAl': 'Annulla',
    'menu.yinele': 'Ripeti',
    'menu.kes': 'Taglia',
    'menu.kopyala': 'Copia',
    'menu.yapistir': 'Incolla',
    'menu.tumunuSec': 'Seleziona tutto',
    'menu.gorunum': 'Visualizza',
    'menu.yenile': 'Ricarica',
    'menu.onbelleksizYenile': 'Ricarica ignorando la cache',
    'menu.yakinlastir': 'Ingrandisci',
    'menu.uzaklastir': 'Riduci',
    'menu.normalBoyut': 'Dimensione reale',
    'menu.tamEkran': 'Schermo intero',
    'menu.gelistirici': 'Strumenti per sviluppatori',
    'menu.arayuzGelistirici': 'Strumenti per sviluppatori dell’interfaccia',
    'menu.gecmis': 'Cronologia',
    'menu.geri': 'Indietro',
    'menu.ileri': 'Avanti',
    'menu.gecmisiGoster': 'Mostra cronologia',
    'menu.indirilenler': 'Download',
    'menu.yerImleri': 'Preferiti',
    'menu.yerImiEkle': 'Aggiungi questa pagina ai preferiti',
    'menu.yerImleriniGoster': 'Mostra preferiti',
    'menu.yerImleriCubugu': 'Barra dei preferiti',
    'menu.sekmeler': 'Schede',
    'menu.sonrakiSekme': 'Scheda successiva',
    'menu.oncekiSekme': 'Scheda precedente',
    'menu.nSekme': 'Scheda {n}',
    'menu.sonSekme': 'Ultima scheda',
    'menu.yardim': 'Aiuto',
    'menu.ayarlar': 'Impostazioni',
    'menu.hakkinda': 'Informazioni su Girginos Browser',
    'hakkinda.detay': 'Un browser attento alla privacy.',
    'menu.yazdir': 'Stampa…',
    'menu.sayfayiKaydet': 'Salva pagina con nome…',
    'menu.digerAraclar': 'Altri strumenti',
    'menu.yakinlastirma': 'Zoom',
    'menu.veriSil': 'Elimina dati di navigazione…',
    'arac.menu': 'Menu',

    'baglam.baglantiYeniSekme': 'Apri link in una nuova scheda',
    'baglam.baglantiKopyala': 'Copia indirizzo del link',
    'baglam.gorselYeniSekme': 'Apri immagine in una nuova scheda',
    'baglam.gorselKopyala': 'Copia indirizzo dell’immagine',
    'baglam.gorselKaydet': 'Salva immagine',
    'baglam.ara': 'Cerca «{q}»',
    'baglam.kaynak': 'Visualizza sorgente pagina',
    'baglam.incele': 'Ispeziona elemento',

    'dialog.iptal': 'Annulla',
    'dialog.ac': 'Apri',
    'dialog.disBaslik': 'Esci da Girginos Browser',
    'dialog.disMesaj': 'Questo link «{sema}» verrà aperto in un’altra applicazione.',
    'dialog.reddet': 'Blocca',
    'dialog.izinVer': 'Consenti',
    'dialog.izinBaslik': 'Richiesta di autorizzazione',
    'dialog.izinMesaj': '{origin} vuole usare:',
    'dialog.izinHatirla': 'Ricorda la mia scelta per questo sito',
    'dialog.calistirBaslik': 'Questo file è eseguibile',
    'dialog.calistirMesaj': 'Questo file potrebbe danneggiare il computer.',
    'dialog.calistirDevam': 'Esegui comunque',
    'dialog.kaynak': 'Origine',

    'izin.notifications': 'le notifiche',
    'izin.geolocation': 'la tua posizione',
    'izin.media': 'fotocamera e microfono',
    'izin.midi': 'dispositivi MIDI',
    'izin.midiSysex': 'dispositivi MIDI',
    'izin.clipboard-read': 'leggere gli appunti',
    'izin.display-capture': 'la condivisione dello schermo',
    'izin.openExternal': 'aprire un’altra applicazione',
    'izin.idle-detection': 'il rilevamento di inattività',
    'izin.pointerLock': 'bloccare il puntatore',
    'izin.fullscreen': 'lo schermo intero',

    'arac.geri': 'Indietro',
    'arac.ileri': 'Avanti',
    'arac.yenile': 'Ricarica',
    'arac.durdur': 'Interrompi',
    'arac.anasayfa': 'Home',
    'arac.yeniSekme': 'Nuova scheda',
    'arac.sekmeyiKapat': 'Chiudi scheda',
    'arac.gecmis': 'Cronologia',
    'arac.indirilenler': 'Download',
    'arac.ayarlar': 'Impostazioni',
    'arac.adresIpucu': 'Cerca o inserisci un indirizzo',
    'arac.yerImiEkle': 'Aggiungi ai preferiti',
    'arac.yerImiCikar': 'Rimuovi dai preferiti',
    'arac.kalkanAcik': '{n} tracker bloccati — clicca per disattivare',
    'arac.kalkanKapali': 'Blocco disattivato su questo sito — clicca per attivare',
    'arac.guvenli': 'Connessione cifrata (HTTPS)',
    'arac.guvensiz': 'Connessione non cifrata',
    'arac.yeniSekmeBaslik': 'Nuova scheda',
    'arac.adsiz': 'Senza titolo',

    'bul.ipucu': 'Trova nella pagina',
    'bul.onceki': 'Precedente',
    'bul.sonraki': 'Successivo',
    'bul.kapat': 'Chiudi',

    'panel.gecmis': 'Cronologia',
    'panel.yerImleri': 'Preferiti',
    'panel.indirilenler': 'Download',
    'panel.ayarlar': 'Impostazioni',
    'panel.kapat': 'Chiudi pannello',
    'panel.kaldir': 'Rimuovi',
    'gecmis.ara': 'Cerca nella cronologia',
    'gecmis.temizle': 'Cancella cronologia',
    'gecmis.bos': 'La cronologia è vuota.',
    'gecmis.eslesmeYok': 'Nessuna voce corrispondente.',
    'gecmis.bugun': 'Oggi',
    'gecmis.dun': 'Ieri',
    'yerimi.bos': 'Non hai ancora preferiti.',
    'yerimi.cubukBos': 'Nessun preferito — premi Ctrl+D per aggiungere questa pagina',
    'yerimi.tumu': 'Tutti i preferiti',
    'yerimi.ac': 'Apri',
    'yerimi.yeniSekmedeAc': 'Apri in una nuova scheda',
    'yerimi.adresiKopyala': 'Copia indirizzo',
    'yerimi.duzenle': 'Rinomina…',
    'yerimi.cubuguGizle': 'Nascondi la barra dei preferiti',

    'indirme.bos': 'Ancora nessun download.',
    'indirme.devam': 'Download in corso',
    'indirme.tamam': 'Completato',
    'indirme.iptal': 'Annullato',
    'indirme.hata': 'Non riuscito',
    'indirme.kesildi': 'Interrotto',
    'indirme.ac': 'Apri',
    'indirme.klasor': 'Mostra nella cartella',
    'indirme.tumunuGoster': 'Mostra tutto',

    'ayar.engellenenSayi': 'Tracker bloccati finora',
    'ayar.yukluAlan': 'Domini caricati dalle liste',
    'ayar.yerImiSayi': 'Preferiti',
    'ayar.bolumArama': 'Ricerca e avvio',
    'ayar.dil': 'Lingua',
    'ayar.dilAciklama': 'Menu, pannelli e pagine di errore usano questa lingua.',
    'ayar.dilSistem': 'Lingua di sistema',
    'ayar.aramaMotoru': 'Motore di ricerca',
    'ayar.aramaMotoruAciklama': 'Le ricerche digitate nella barra degli indirizzi vanno qui.',
    'ayar.anasayfa': 'Pagina iniziale',
    'ayar.anasayfaAciklama': 'L’indirizzo aperto dal pulsante Home.',
    'ayar.anasayfaIpucu': 'Lascia vuoto per la pagina nuova scheda',
    'ayar.bolumGizlilik': 'Privacy',
    'ayar.engelleyici': 'Blocco tracker e pubblicità',
    'ayar.engelleyiciAciklama': 'Annulla le richieste ai domini pubblicitari e di tracciamento noti.',
    'ayar.dnt': 'Invia segnale di non tracciamento',
    'ayar.dntAciklama': 'Aggiunge le intestazioni DNT e Sec-GPC a ogni richiesta.',
    'ayar.ucuncuTarafCerez': 'Blocca i cookie di terze parti',
    'ayar.ucuncuTarafCerezAciklama': 'Il principale veicolo del tracciamento tra siti. Se un sito smette di funzionare, puoi consentirlo dal menu del lucchetto nella barra degli indirizzi.',
    'ayar.kapanistaCerezSil': 'Elimina i cookie alla chiusura',
    'ayar.kapanistaCerezSilAciklama': 'I cookie dei siti nei preferiti vengono conservati, così resti connesso.',
    'ayar.gecmisiKaydet': 'Salva cronologia',
    'ayar.gecmisiKaydetAciklama': 'Se disattivato, le pagine visitate non vengono mai scritte su disco.',
    'ayar.cerezler': 'Cookie e cache',
    'ayar.cerezlerAciklama': 'Elimina cookie, archiviazione locale e cache di tutti i siti.',
    'ayar.veriTemizle': 'Cancella dati',
    'ayar.temizleniyor': 'Cancellazione…',
    'ayar.temizlendi': 'Cancellato',
    'ayar.siteIzinleri': 'Autorizzazioni dei siti',
    'ayar.siteIzinleriAciklama': 'Elimina le scelte memorizzate su posizione, fotocamera e notifiche, e le eccezioni del blocco.',
    'ayar.izinSifirla': 'Reimposta autorizzazioni',
    'ayar.sifirlandi': 'Reimpostato',
    'ayar.bolumListeler': 'Liste di filtri',
    'ayar.listeKullan': 'Usa le liste scaricate',
    'ayar.listeKullanAciklama': 'Vengono bloccati anche i domini di liste come EasyList. Se disattivato vale solo la lista integrata.',
    'ayar.otomatikGuncelle': 'Aggiorna automaticamente',
    'ayar.otomatikGuncelleAciklama': 'Le liste si aggiornano in background con l’intervallo che dichiarano (di solito ogni 4 giorni).',
    'ayar.listeYenile': 'Aggiorna liste',
    'ayar.listeYenileAciklama': 'Le riscarica tutte subito.',
    'ayar.simdiGuncelle': 'Aggiorna ora',
    'ayar.guncelleniyor': 'Aggiornamento…',
    'ayar.listeEkle': 'Aggiungi la tua lista',
    'ayar.listeEkleAciklama': 'Un indirizzo https in formato Adblock Plus, hosts o dominio semplice.',
    'ayar.listeEkleIpucu': 'https://... indirizzo della lista',
    'ayar.ekle': 'Aggiungi',
    'ayar.ekleniyor': 'Aggiunta…',
    'ayar.listeKaldir': 'Rimuovi',
    'ayar.listeIndirilmedi': 'Non ancora scaricata',
    'ayar.listeHata': 'Aggiornamento non riuscito: {hata}',
    'ayar.listeDurum': '{n} domini · aggiornata {ne}',
    'ayar.bugun': 'oggi',
    'ayar.dun': 'ieri',
    'ayar.gunOnce': '{n} giorni fa',
    'ayar.bolumIzinler': 'Richieste di autorizzazione',
    'ayar.izinSor': 'Chiedi ogni volta',
    'ayar.izinVer': 'Consenti sempre',
    'ayar.izinRet': 'Blocca sempre',
    'ayar.izinSatir': 'Cosa fare quando un sito chiede {izin}?',
    'ayar.bolumGorunum': 'Aspetto',
    'ayar.yerImleriCubugu': 'Barra dei preferiti',
    'ayar.yerImleriCubuguAciklama': 'Mostra i preferiti sotto la barra degli strumenti.',
    'ayar.yenidenBaslat': 'Riavvia Girginos Browser per applicare la lingua.',

    'liste.easylist': 'Pubblicità',
    'liste.easyprivacy': 'Tracker',
    'liste.hataHttps': 'Si possono aggiungere solo indirizzi https://.',
    'liste.hataVar': 'Questa lista è già presente.',
    /* --- site bilgisi menusu --- */
    'site.baglantiGuvenli': 'Connessione sicura',
    'site.baglantiGuvensiz': 'Connessione non sicura',
    'site.guvensizUyari': 'Le informazioni inserite in questa pagina vengono inviate senza cifratura.',
    'site.sertifikaVeren': 'Emesso da: {ad}',
    'site.sertifikaSahip': 'Emesso per: {ad}',
    'site.sertifikaGecerlilik': 'Validità: {bas} – {bit}',
    'site.parmakIzi': 'Copia impronta',
    'site.sertifikaYok': 'Nessuna informazione sul certificato',
    'site.cerezler': 'Cookie e dati dei siti',
    'site.cerezSayisi': '{n} cookie',
    'site.ucuncuTarafCerez': 'Consenti i cookie di terze parti',
    'site.veriSil': 'Elimina i dati di questo sito',
    'site.engelleyici': 'Blocco tracker',
    'site.izinSifirla': 'Reimposta le autorizzazioni di questo sito',
    'site.ayarlar': 'Impostazioni sito',
    /* --- guncelleme --- */
    'menu.guncellemeDenetle': 'Controlla aggiornamenti',
    'ayar.bolumGuncelleme': 'Aggiornamenti',
    'ayar.surum': 'Versione',
    'ayar.guncellemeKontrolEt': 'Controlla ora',
    'ayar.guncellemeIndirDugme': 'Scarica',
    'ayar.guncellemeKur': 'Riavvia e installa',
    'ayar.guncellemeOtoKontrol': 'Controlla automaticamente gli aggiornamenti',
    'ayar.guncellemeOtoKontrolAciklama': 'Le informazioni di rilascio firmate vengono controllate all’avvio e ogni 6 ore.',
    'ayar.guncellemeOtoIndir': 'Scarica automaticamente',
    'ayar.guncellemeOtoIndirAciklama': 'La nuova versione viene scaricata in background; l’installazione richiede comunque la tua conferma.',
    'ayar.guncellemeKanal': 'Canale di aggiornamento',
    'ayar.guncellemeKanalAciklama': 'Il canale beta riceve prima le novità ed è meno testato.',
    'ayar.kanalKararli': 'Stabile',
    'ayar.kanalBeta': 'Beta',
    'guncelleme.kapali': 'Aggiornamenti disattivati: nessuna chiave di rilascio o indirizzo configurato.',
    'guncelleme.paketlenmemis': 'In esecuzione dai sorgenti; gli aggiornamenti valgono solo per una versione installata.',
    'guncelleme.bosta': 'Non ancora controllato.',
    'guncelleme.kontrol': 'Controllo in corso…',
    'guncelleme.guncel': 'Stai usando l’ultima versione.',
    'guncelleme.bulundu': 'La versione {surum} è disponibile.',
    'guncelleme.iniyor': 'Download… {n} %',
    'guncelleme.hazir': 'La versione {surum} è pronta per l’installazione.',
    'guncelleme.hata': 'Controllo non riuscito: {sebep}',
    /* --- yeni sekme ve hata sayfasi --- */
    'sayfa.tekrarDene': 'Riprova',
    'sayfa.oneriYenile': 'Ricarica la pagina',
    'sayfa.oneriAdres': 'Controlla eventuali errori di battitura nell’indirizzo',
    'sayfa.oneriBaglanti': 'Controlla la connessione a internet',
    'sayfa.oneriBilgiGirme': 'Non inserire informazioni sensibili qui',
    'hata.dns.baslik': 'Server non trovato',
    'hata.dns.metin': 'Non è stato possibile risolvere l’IP di questo indirizzo. Il dominio potrebbe essere errato o offline.',
    'hata.cevrimdisi.baslik': 'Nessuna connessione a internet',
    'hata.cevrimdisi.metin': 'Il dispositivo non sembra connesso a una rete.',
    'hata.baglanti.baslik': 'Impossibile connettersi',
    'hata.baglanti.metin': 'Il server ha rifiutato la connessione oppure è caduta inaspettatamente.',
    'hata.zamanAsimi.baslik': 'Connessione scaduta',
    'hata.zamanAsimi.metin': 'Il server non ha risposto in tempo ragionevole.',
    'hata.sertifikaAd.baslik': 'Il certificato non appartiene a questo sito',
    'hata.sertifikaAd.metin': 'Il dominio nel certificato non corrisponde all’indirizzo inserito.',
    'hata.sertifikaSure.baslik': 'Il certificato è scaduto',
    'hata.sertifikaSure.metin': 'Il certificato di sicurezza del server non è più valido. Controlla anche la data del dispositivo.',
    'hata.sertifikaMakam.baslik': 'Impossibile verificare il certificato',
    'hata.sertifikaMakam.metin': 'L’autorità che ha firmato il certificato non è riconosciuta. La connessione potrebbe essere intercettata.',
    'hata.cokme.baslik': 'La scheda ha smesso di rispondere',
    'hata.cokme.metin': 'La pagina si è chiusa in modo inaspettato.',
    'hata.bilinmeyen.baslik': 'Impossibile aprire questa pagina',
    'hata.bilinmeyen.metin': 'Si è verificato un problema sconosciuto durante il caricamento.',
    'yenisekme.ara': 'Cerca',
    'yenisekme.sik': 'Siti frequenti',
    'yenisekme.oneCikan': 'In evidenza',
    'yenisekme.kisayolEkle': '+ Aggiungi scorciatoia',
    'yenisekme.kisayolIpucu': 'esempio.it — premi Invio per aggiungere',
    'yenisekme.gecersizAdres': 'Inserisci un indirizzo valido',
    'yenisekme.kisayol': 'Scorciatoia',
    'yenisekme.bosNot': 'I siti che visiti più spesso compariranno qui.',
    'yenisekme.engellendi': 'Girginos Browser ha bloccato finora {n} richieste di tracker.',
    'yenisekme.engelleyiciAcik': 'Il blocco dei tracker è attivo. Le richieste bloccate saranno conteggiate qui.',
    /* --- adres onerileri --- */
    'oneri.ara': 'Cerca con {motor}',
    'oneri.adreseGit': 'Vai all’indirizzo',
    /* --- gorunum --- */
    'ayar.tema': 'Aspetto',
    'ayar.temaAciklama': 'Interfaccia, pagine interne e menu seguono questa scelta.',
    'ayar.temaSistem': 'Come il sistema',
    'ayar.temaAcik': 'Chiaro',
    'ayar.temaKoyu': 'Scuro',
    /* --- katman: izin kutusu --- */
    'dialog.izinIstiyor': 'richiede:',
    'izin.storage-access': 'accesso all’archiviazione',
    /* --- site izin duvari --- */
    'panel.siteIzinleri': 'Autorizzazioni del sito',
    'izin.siteYok': 'Nessuna autorizzazione per questa pagina.',
    'izin.durumSor': 'Chiedi',
    'izin.durumIzin': 'Consenti',
    'izin.durumRet': 'Blocca',
    'izin.varsayilanEk': 'predefinito',
    'izin.siteKarari': 'Impostato da te per questo sito.',
    'izin.varsayilanIzleniyor': 'Si applica il valore predefinito.',
    'izin.bilinmeyen': 'questa autorizzazione ({ad})'
  }
};
