'use strict';

module.exports = {
  ad: '日本語',
  yon: 'ltr',
  yerel: 'ja-JP',
  metin: {
    'menu.dosya': 'ファイル',
    'menu.yeniSekme': '新しいタブ',
    'menu.sekmeyiKapat': 'タブを閉じる',
    'menu.adresCubugu': 'アドレスバーへ移動',
    'menu.sayfadaBul': 'ページ内を検索',
    'menu.cikis': '終了',
    'menu.duzen': '編集',
    'menu.geriAl': '元に戻す',
    'menu.yinele': 'やり直し',
    'menu.kes': '切り取り',
    'menu.kopyala': 'コピー',
    'menu.yapistir': '貼り付け',
    'menu.tumunuSec': 'すべて選択',
    'menu.gorunum': '表示',
    'menu.yenile': '再読み込み',
    'menu.onbelleksizYenile': 'キャッシュを無視して再読み込み',
    'menu.yakinlastir': '拡大',
    'menu.uzaklastir': '縮小',
    'menu.normalBoyut': '実際のサイズ',
    'menu.tamEkran': '全画面表示',
    'menu.gelistirici': '開発者ツール',
    'menu.arayuzGelistirici': 'UI の開発者ツール',
    'menu.gecmis': '履歴',
    'menu.geri': '戻る',
    'menu.ileri': '進む',
    'menu.gecmisiGoster': '履歴を表示',
    'menu.indirilenler': 'ダウンロード',
    'menu.yerImleri': 'ブックマーク',
    'menu.yerImiEkle': 'このページをブックマーク',
    'menu.yerImleriniGoster': 'ブックマークを表示',
    'menu.yerImleriCubugu': 'ブックマークバー',
    'menu.sekmeler': 'タブ',
    'menu.sonrakiSekme': '次のタブ',
    'menu.oncekiSekme': '前のタブ',
    'menu.nSekme': 'タブ {n}',
    'menu.sonSekme': '最後のタブ',
    'menu.yardim': 'ヘルプ',
    'menu.ayarlar': '設定',
    'menu.hakkinda': 'Girginos Browser について',
    'hakkinda.detay': 'プライバシー重視のブラウザーです。',
    'menu.yazdir': '印刷…',
    'menu.sayfayiKaydet': 'ページを名前を付けて保存…',
    'menu.digerAraclar': 'その他のツール',
    'menu.yakinlastirma': 'ズーム',
    'menu.veriSil': '閲覧データを削除…',
    'arac.menu': 'メニュー',

    'baglam.baglantiYeniSekme': 'リンクを新しいタブで開く',
    'baglam.baglantiKopyala': 'リンクのアドレスをコピー',
    'baglam.gorselYeniSekme': '画像を新しいタブで開く',
    'baglam.gorselKopyala': '画像のアドレスをコピー',
    'baglam.gorselKaydet': '画像を保存',
    'baglam.ara': '「{q}」を検索',
    'baglam.kaynak': 'ページのソースを表示',
    'baglam.incele': '要素を検証',

    'dialog.iptal': 'キャンセル',
    'dialog.ac': '開く',
    'dialog.disBaslik': 'Girginos Browser の外へ',
    'dialog.disMesaj': 'この「{sema}」リンクは別のアプリで開かれます。',
    'dialog.reddet': 'ブロック',
    'dialog.izinVer': '許可',
    'dialog.izinBaslik': '権限の要求',
    'dialog.izinMesaj': '{origin} が次の使用を求めています:',
    'dialog.izinHatirla': 'このサイトでの選択を記憶する',
    'dialog.calistirBaslik': 'このファイルは実行可能です',
    'dialog.calistirMesaj': 'このファイルはコンピューターに害を与える可能性があります。',
    'dialog.calistirDevam': 'それでも実行',
    'dialog.kaynak': '取得元',

    'izin.notifications': '通知の送信',
    'izin.geolocation': '位置情報',
    'izin.media': 'カメラとマイク',
    'izin.midi': 'MIDI デバイス',
    'izin.midiSysex': 'MIDI デバイス',
    'izin.clipboard-read': 'クリップボードの読み取り',
    'izin.display-capture': '画面の共有',
    'izin.openExternal': '別のアプリを開くこと',
    'izin.idle-detection': 'アイドル検出',
    'izin.pointerLock': 'マウスポインターの固定',
    'izin.fullscreen': '全画面表示',

    'arac.geri': '戻る',
    'arac.ileri': '進む',
    'arac.yenile': '再読み込み',
    'arac.durdur': '停止',
    'arac.anasayfa': 'ホーム',
    'arac.yeniSekme': '新しいタブ',
    'arac.sekmeyiKapat': 'タブを閉じる',
    'arac.gecmis': '履歴',
    'arac.indirilenler': 'ダウンロード',
    'arac.ayarlar': '設定',
    'arac.adresIpucu': '検索またはアドレスを入力',
    'arac.yerImiEkle': 'ブックマークに追加',
    'arac.yerImiCikar': 'ブックマークから削除',
    'arac.kalkanAcik': '{n} 件のトラッカーをブロック — クリックで無効化',
    'arac.kalkanKapali': 'このサイトではブロックが無効 — クリックで有効化',
    'arac.guvenli': '接続は暗号化されています（HTTPS）',
    'arac.guvensiz': '接続は暗号化されていません',
    'arac.yeniSekmeBaslik': '新しいタブ',
    'arac.adsiz': '無題',

    'bul.ipucu': 'ページ内を検索',
    'bul.onceki': '前へ',
    'bul.sonraki': '次へ',
    'bul.kapat': '閉じる',

    'panel.gecmis': '履歴',
    'panel.yerImleri': 'ブックマーク',
    'panel.indirilenler': 'ダウンロード',
    'panel.ayarlar': '設定',
    'panel.kapat': 'パネルを閉じる',
    'panel.kaldir': '削除',
    'gecmis.ara': '履歴を検索',
    'gecmis.temizle': '履歴を消去',
    'gecmis.bos': '履歴は空です。',
    'gecmis.eslesmeYok': '一致する項目はありません。',
    'gecmis.bugun': '今日',
    'gecmis.dun': '昨日',
    'yerimi.bos': 'まだブックマークがありません。',
    'yerimi.cubukBos': 'ブックマークなし — Ctrl+D でこのページを追加',
    'yerimi.tumu': 'すべてのブックマーク',
    'yerimi.ac': '開く',
    'yerimi.yeniSekmedeAc': '新しいタブで開く',
    'yerimi.adresiKopyala': 'アドレスをコピー',
    'yerimi.duzenle': '名前を変更…',
    'yerimi.cubuguGizle': 'ブックマークバーを非表示',

    'indirme.bos': 'まだダウンロードはありません。',
    'indirme.devam': 'ダウンロード中',
    'indirme.tamam': '完了',
    'indirme.iptal': 'キャンセル済み',
    'indirme.hata': '失敗',
    'indirme.kesildi': '中断',
    'indirme.ac': '開く',
    'indirme.klasor': 'フォルダーに表示',
    'indirme.tumunuGoster': 'すべて表示',

    'ayar.engellenenSayi': 'これまでにブロックしたトラッカー',
    'ayar.yukluAlan': 'リストから読み込んだドメイン',
    'ayar.yerImiSayi': 'ブックマーク',
    'ayar.bolumArama': '検索と起動',
    'ayar.dil': '言語',
    'ayar.dilAciklama': 'メニュー、パネル、エラーページはこの言語で表示されます。',
    'ayar.dilSistem': 'システムの言語',
    'ayar.aramaMotoru': '検索エンジン',
    'ayar.aramaMotoruAciklama': 'アドレスバーに入力した検索はここへ送られます。',
    'ayar.anasayfa': 'ホームページ',
    'ayar.anasayfaAciklama': 'ホームボタンが開くアドレス。',
    'ayar.anasayfaIpucu': '空欄にすると新しいタブページ',
    'ayar.bolumGizlilik': 'プライバシー',
    'ayar.engelleyici': 'トラッカーと広告のブロック',
    'ayar.engelleyiciAciklama': '既知の広告・追跡ドメインへのリクエストを中止します。',
    'ayar.dnt': 'トラッキング拒否シグナルを送信',
    'ayar.dntAciklama': 'すべてのリクエストに DNT と Sec-GPC ヘッダーを追加します。',
    'ayar.gecmisiKaydet': '履歴を保存',
    'ayar.gecmisiKaydetAciklama': 'オフのとき、訪問したページはディスクに書き込まれません。',
    'ayar.cerezler': 'Cookie とキャッシュ',
    'ayar.cerezlerAciklama': 'すべてのサイトの Cookie、ローカルストレージ、キャッシュを削除します。',
    'ayar.veriTemizle': 'データを消去',
    'ayar.temizleniyor': '消去中…',
    'ayar.temizlendi': '消去しました',
    'ayar.siteIzinleri': 'サイトの権限',
    'ayar.siteIzinleriAciklama': '位置情報・カメラ・通知の記憶した選択と、ブロックの例外を削除します。',
    'ayar.izinSifirla': 'サイトの権限をリセット',
    'ayar.sifirlandi': 'リセットしました',
    'ayar.bolumListeler': 'フィルターリスト',
    'ayar.listeKullan': 'ダウンロードしたリストを使う',
    'ayar.listeKullanAciklama': 'EasyList などのリストのドメインもブロックします。オフのときは内蔵リストのみ有効です。',
    'ayar.otomatikGuncelle': '自動的に更新',
    'ayar.otomatikGuncelleAciklama': 'リストは指定された間隔（通常 4 日ごと）でバックグラウンド更新されます。',
    'ayar.listeYenile': 'リストを更新',
    'ayar.listeYenileAciklama': 'すべてを今すぐ再ダウンロードします。',
    'ayar.simdiGuncelle': '今すぐ更新',
    'ayar.guncelleniyor': '更新中…',
    'ayar.listeEkle': '独自のリストを追加',
    'ayar.listeEkleAciklama': 'Adblock Plus、hosts、または単純なドメイン形式の https アドレス。',
    'ayar.listeEkleIpucu': 'https://... フィルターリストのアドレス',
    'ayar.ekle': '追加',
    'ayar.ekleniyor': '追加中…',
    'ayar.listeKaldir': '削除',
    'ayar.listeIndirilmedi': 'まだダウンロードされていません',
    'ayar.listeHata': '更新できませんでした: {hata}',
    'ayar.listeDurum': '{n} ドメイン · {ne}更新',
    'ayar.bugun': '今日',
    'ayar.dun': '昨日',
    'ayar.gunOnce': '{n} 日前',
    'ayar.bolumIzinler': '権限の要求',
    'ayar.izinSor': '毎回確認する',
    'ayar.izinVer': '常に許可',
    'ayar.izinRet': '常にブロック',
    'ayar.izinSatir': 'サイトが{izin}を求めたときの動作',
    'ayar.bolumGorunum': '外観',
    'ayar.yerImleriCubugu': 'ブックマークバー',
    'ayar.yerImleriCubuguAciklama': 'ツールバーの下にブックマークを表示します。',
    'ayar.yenidenBaslat': '言語を適用するには Girginos Browser を再起動してください。',

    'liste.easylist': '広告',
    'liste.easyprivacy': 'トラッカー',
    'liste.hataHttps': 'https:// のアドレスのみ追加できます。',
    'liste.hataVar': 'このリストはすでに追加されています。',
    /* --- site bilgisi menusu --- */
    'site.baglantiGuvenli': '接続は保護されています',
    'site.baglantiGuvensiz': '接続は保護されていません',
    'site.guvensizUyari': 'このページに入力した情報は暗号化されずに送信されます。',
    'site.sertifikaVeren': '発行者: {ad}',
    'site.sertifikaSahip': '発行先: {ad}',
    'site.sertifikaGecerlilik': '有効期間: {bas} – {bit}',
    'site.parmakIzi': 'フィンガープリントをコピー',
    'site.sertifikaYok': '証明書情報がありません',
    'site.cerezler': 'Cookie とサイトデータ',
    'site.cerezSayisi': 'Cookie {n} 件',
    'site.veriSil': 'このサイトのデータを削除',
    'site.engelleyici': 'トラッカーのブロック',
    'site.izinSifirla': 'このサイトの権限をリセット',
    'site.ayarlar': 'サイトの設定',
    /* --- guncelleme --- */
    'menu.guncellemeDenetle': '更新を確認',
    'ayar.bolumGuncelleme': '更新',
    'ayar.surum': 'バージョン',
    'ayar.guncellemeKontrolEt': '今すぐ確認',
    'ayar.guncellemeIndirDugme': 'ダウンロード',
    'ayar.guncellemeKur': '再起動してインストール',
    'ayar.guncellemeOtoKontrol': '更新を自動的に確認',
    'ayar.guncellemeOtoKontrolAciklama': '署名済みのリリース情報を起動時と 6 時間ごとに確認します。',
    'ayar.guncellemeOtoIndir': '自動的にダウンロード',
    'ayar.guncellemeOtoIndirAciklama': '新しいバージョンはバックグラウンドでダウンロードされます。インストールには確認が必要です。',
    'ayar.guncellemeKanal': '更新チャンネル',
    'ayar.guncellemeKanalAciklama': 'ベータチャンネルは新機能を早く受け取りますが、検証は少なめです。',
    'ayar.kanalKararli': '安定版',
    'ayar.kanalBeta': 'ベータ版',
    'guncelleme.kapali': '更新は無効です: リリース鍵または配信先が設定されていません。',
    'guncelleme.paketlenmemis': 'ソースから実行中です。更新はインストール版にのみ適用されます。',
    'guncelleme.bosta': '未確認です。',
    'guncelleme.kontrol': '確認中…',
    'guncelleme.guncel': '最新バージョンをお使いです。',
    'guncelleme.bulundu': 'バージョン {surum} が公開されました。',
    'guncelleme.iniyor': 'ダウンロード中… {n}%',
    'guncelleme.hazir': 'バージョン {surum} をインストールできます。',
    'guncelleme.hata': '確認できませんでした: {sebep}',
    /* --- yeni sekme ve hata sayfasi --- */
    'sayfa.tekrarDene': '再試行',
    'sayfa.oneriYenile': 'ページを再読み込みしてください',
    'sayfa.oneriAdres': 'アドレスの入力ミスを確認してください',
    'sayfa.oneriBaglanti': 'インターネット接続を確認してください',
    'sayfa.oneriBilgiGirme': 'このページに重要な情報を入力しないでください',
    'hata.dns.baslik': 'サーバーが見つかりません',
    'hata.dns.metin': 'このアドレスの IP を解決できませんでした。ドメイン名の誤りか、公開されていない可能性があります。',
    'hata.cevrimdisi.baslik': 'インターネットに接続していません',
    'hata.cevrimdisi.metin': 'デバイスがネットワークに接続されていないようです。',
    'hata.baglanti.baslik': '接続できませんでした',
    'hata.baglanti.metin': 'サーバーが接続を拒否したか、接続が予期せず切断されました。',
    'hata.zamanAsimi.baslik': '接続がタイムアウトしました',
    'hata.zamanAsimi.metin': 'サーバーから妥当な時間内に応答がありませんでした。',
    'hata.sertifikaAd.baslik': '証明書がこのサイトのものではありません',
    'hata.sertifikaAd.metin': 'サーバー証明書のドメインが入力したアドレスと一致しません。',
    'hata.sertifikaSure.baslik': '証明書の有効期限が切れています',
    'hata.sertifikaSure.metin': 'サーバーのセキュリティ証明書は無効です。デバイスの日付も確認してください。',
    'hata.sertifikaMakam.baslik': '証明書を検証できませんでした',
    'hata.sertifikaMakam.metin': '証明書に署名した機関が認識できません。通信が傍受されている可能性があります。',
    'hata.cokme.baslik': 'タブが応答しなくなりました',
    'hata.cokme.metin': 'ページが予期せず終了しました。',
    'hata.bilinmeyen.baslik': 'このページを開けませんでした',
    'hata.bilinmeyen.metin': 'ページの読み込み中に不明な問題が発生しました。',
    'yenisekme.ara': '検索',
    'yenisekme.sik': 'よく見るサイト',
    'yenisekme.oneCikan': 'おすすめ',
    'yenisekme.kisayolEkle': '+ ショートカットを追加',
    'yenisekme.kisayolIpucu': 'example.com — Enter で追加',
    'yenisekme.gecersizAdres': '有効なアドレスを入力してください',
    'yenisekme.kisayol': 'ショートカット',
    'yenisekme.bosNot': '閲覧するにつれて、よく訪れるサイトがここに表示されます。',
    'yenisekme.engellendi': 'Girginos Browser はこれまでに {n} 件のトラッカー要求をブロックしました。',
    'yenisekme.engelleyiciAcik': 'トラッカーのブロックは有効です。ブロックした要求はここに集計されます。',
    /* --- adres onerileri --- */
    'oneri.ara': '{motor} で検索',
    'oneri.adreseGit': 'アドレスを開く',
    /* --- gorunum --- */
    'ayar.tema': '外観',
    'ayar.temaAciklama': '画面・内蔵ページ・メニューがこの設定に従います。',
    'ayar.temaSistem': 'システムに合わせる',
    'ayar.temaAcik': 'ライト',
    'ayar.temaKoyu': 'ダーク'
  }
};
