'use strict';

module.exports = {
  ad: 'Português',
  yon: 'ltr',
  yerel: 'pt-BR',
  metin: {
    'menu.dosya': 'Arquivo',
    'menu.yeniSekme': 'Nova aba',
    'menu.sekmeyiKapat': 'Fechar aba',
    'menu.adresCubugu': 'Ir para a barra de endereços',
    'menu.sayfadaBul': 'Localizar na página',
    'menu.cikis': 'Sair',
    'menu.duzen': 'Editar',
    'menu.geriAl': 'Desfazer',
    'menu.yinele': 'Refazer',
    'menu.kes': 'Recortar',
    'menu.kopyala': 'Copiar',
    'menu.yapistir': 'Colar',
    'menu.tumunuSec': 'Selecionar tudo',
    'menu.gorunum': 'Exibir',
    'menu.yenile': 'Recarregar',
    'menu.onbelleksizYenile': 'Recarregar ignorando o cache',
    'menu.yakinlastir': 'Ampliar',
    'menu.uzaklastir': 'Reduzir',
    'menu.normalBoyut': 'Tamanho real',
    'menu.tamEkran': 'Tela cheia',
    'menu.gelistirici': 'Ferramentas do desenvolvedor',
    'menu.arayuzGelistirici': 'Ferramentas do desenvolvedor da interface',
    'menu.gecmis': 'Histórico',
    'menu.geri': 'Voltar',
    'menu.ileri': 'Avançar',
    'menu.gecmisiGoster': 'Mostrar histórico',
    'menu.indirilenler': 'Downloads',
    'menu.yerImleri': 'Favoritos',
    'menu.yerImiEkle': 'Adicionar esta página aos favoritos',
    'menu.yerImleriniGoster': 'Mostrar favoritos',
    'menu.yerImleriCubugu': 'Barra de favoritos',
    'menu.sekmeler': 'Abas',
    'menu.sonrakiSekme': 'Próxima aba',
    'menu.oncekiSekme': 'Aba anterior',
    'menu.nSekme': 'Aba {n}',
    'menu.sonSekme': 'Última aba',
    'menu.yardim': 'Ajuda',
    'menu.ayarlar': 'Configurações',
    'menu.hakkinda': 'Sobre o Girginos Browser',
    'hakkinda.detay': 'Um navegador focado em privacidade.',
    'menu.yazdir': 'Imprimir…',
    'menu.sayfayiKaydet': 'Salvar página como…',
    'menu.digerAraclar': 'Mais ferramentas',
    'menu.yakinlastirma': 'Zoom',
    'menu.veriSil': 'Excluir dados de navegação…',
    'arac.onbellek': 'Redefinir o cache',
    'arac.onbellekTemizlendi': 'Cache limpo, página recarregada',
    'arac.onbellekHata': 'Não foi possível limpar o cache',
    'arac.menu': 'Menu',

    'baglam.baglantiYeniSekme': 'Abrir link em nova aba',
    'baglam.baglantiKopyala': 'Copiar endereço do link',
    'baglam.gorselYeniSekme': 'Abrir imagem em nova aba',
    'baglam.gorselKopyala': 'Copiar endereço da imagem',
    'baglam.gorselKaydet': 'Salvar imagem',
    'baglam.ara': 'Pesquisar «{q}»',
    'baglam.kaynak': 'Ver código-fonte',
    'baglam.incele': 'Inspecionar elemento',

    'dialog.iptal': 'Cancelar',
    'dialog.ac': 'Abrir',
    'dialog.disBaslik': 'Sair do Girginos Browser',
    'dialog.disMesaj': 'Este link «{sema}» será aberto em outro aplicativo.',
    'dialog.reddet': 'Bloquear',
    'dialog.izinVer': 'Permitir',
    'dialog.izinBaslik': 'Pedido de permissão',
    'dialog.izinMesaj': '{origin} quer usar:',
    'dialog.izinHatirla': 'Lembrar minha escolha para este site',
    'dialog.calistirBaslik': 'Este arquivo é executável',
    'dialog.calistirMesaj': 'Este arquivo pode danificar seu computador.',
    'dialog.calistirDevam': 'Executar mesmo assim',
    'dialog.kaynak': 'Origem',

    'izin.notifications': 'notificações',
    'izin.geolocation': 'sua localização',
    'izin.media': 'câmera e microfone',
    'izin.midi': 'dispositivos MIDI',
    'izin.midiSysex': 'dispositivos MIDI',
    'izin.clipboard-read': 'ler a área de transferência',
    'izin.display-capture': 'compartilhamento de tela',
    'izin.openExternal': 'abrir outro aplicativo',
    'izin.idle-detection': 'detecção de inatividade',
    'izin.pointerLock': 'travar o ponteiro do mouse',
    'izin.fullscreen': 'tela cheia',

    'arac.geri': 'Voltar',
    'arac.ileri': 'Avançar',
    'arac.yenile': 'Recarregar',
    'arac.durdur': 'Parar',
    'arac.anasayfa': 'Início',
    'arac.yeniSekme': 'Nova aba',
    'arac.sekmeyiKapat': 'Fechar aba',
    'arac.gecmis': 'Histórico',
    'arac.indirilenler': 'Downloads',
    'arac.ayarlar': 'Configurações',
    'arac.adresIpucu': 'Pesquise ou digite um endereço',
    'arac.yerImiEkle': 'Adicionar favorito',
    'arac.yerImiCikar': 'Remover favorito',
    'arac.kalkanAcik': '{n} rastreadores bloqueados — clique para desativar',
    'arac.kalkanKapali': 'Bloqueio desativado neste site — clique para ativar',
    'arac.reklamEngel': 'Bloqueador de anúncios',
    'arac.reklamEngelAcik': 'Bloqueador ativado (todos os sites) — clique para desativar',
    'arac.reklamEngelKapali': 'Bloqueador desativado (todos os sites) — clique para ativar',
    'arac.guvenli': 'Conexão criptografada (HTTPS)',
    'arac.guvensiz': 'Conexão não criptografada',
    'arac.yeniSekmeBaslik': 'Nova aba',
    'arac.adsiz': 'Sem título',

    'bul.ipucu': 'Localizar na página',
    'bul.onceki': 'Anterior',
    'bul.sonraki': 'Próximo',
    'bul.kapat': 'Fechar',

    'panel.gecmis': 'Histórico',
    'panel.yerImleri': 'Favoritos',
    'panel.indirilenler': 'Downloads',
    'panel.ayarlar': 'Configurações',
    'panel.kapat': 'Fechar painel',
    'panel.kaldir': 'Remover',
    'gecmis.ara': 'Pesquisar no histórico',
    'gecmis.temizle': 'Limpar histórico',
    'gecmis.bos': 'Seu histórico está vazio.',
    'gecmis.eslesmeYok': 'Nenhum registro correspondente.',
    'gecmis.bugun': 'Hoje',
    'gecmis.dun': 'Ontem',
    'yerimi.bos': 'Você ainda não tem favoritos.',
    'yerimi.cubukBos': 'Sem favoritos — pressione Ctrl+D para adicionar esta página',
    'yerimi.tumu': 'Todos os favoritos',
    'yerimi.ac': 'Abrir',
    'yerimi.yeniSekmedeAc': 'Abrir em nova aba',
    'yerimi.adresiKopyala': 'Copiar endereço',
    'yerimi.duzenle': 'Renomear…',
    'yerimi.cubuguGizle': 'Ocultar a barra de favoritos',

    'indirme.bos': 'Nenhum download ainda.',
    'indirme.devam': 'Baixando',
    'indirme.tamam': 'Concluído',
    'indirme.iptal': 'Cancelado',
    'indirme.hata': 'Falhou',
    'indirme.kesildi': 'Interrompido',
    'indirme.ac': 'Abrir',
    'indirme.klasor': 'Mostrar na pasta',
    'indirme.tumunuGoster': 'Ver todos',

    'ayar.engellenenSayi': 'Rastreadores bloqueados até agora',
    'ayar.yukluAlan': 'Domínios carregados das listas',
    'ayar.yerImiSayi': 'Favoritos',
    'ayar.bolumArama': 'Busca e inicialização',
    'ayar.dil': 'Idioma',
    'ayar.dilAciklama': 'Menus, painéis e páginas de erro usam este idioma.',
    'ayar.dilSistem': 'Idioma do sistema',
    'ayar.aramaMotoru': 'Mecanismo de busca',
    'ayar.aramaMotoruAciklama': 'As buscas digitadas na barra de endereços vão para cá.',
    'ayar.anasayfa': 'Página inicial',
    'ayar.anasayfaAciklama': 'O endereço aberto pelo botão de início.',
    'ayar.anasayfaIpucu': 'Deixe vazio para a página de nova aba',
    'ayar.bolumGizlilik': 'Privacidade',
    'ayar.engelleyici': 'Bloqueador de rastreadores e anúncios',
    'ayar.engelleyiciAciklama': 'Cancela requisições para domínios conhecidos de publicidade e rastreamento.',
    'ayar.dnt': 'Enviar sinal de não rastrear',
    'ayar.dntAciklama': 'Adiciona os cabeçalhos DNT e Sec-GPC a cada requisição.',
    'ayar.ucuncuTarafCerez': 'Bloquear cookies de terceiros',
    'ayar.ucuncuTarafCerezAciklama': 'O principal veículo do rastreamento entre sites. Se um site parar de funcionar, você pode permiti-lo no menu do cadeado na barra de endereço. A alteração só tem efeito completo após reiniciar.',
    'ayar.kapanistaCerezSil': 'Apagar os cookies ao sair',
    'ayar.kapanistaCerezSilAciklama': 'Os cookies dos sites nos favoritos são mantidos, para você continuar conectado.',
    'ayar.gecmisiKaydet': 'Salvar histórico',
    'ayar.gecmisiKaydetAciklama': 'Quando desligado, as páginas visitadas nunca são gravadas em disco.',
    'ayar.cerezler': 'Cookies e cache',
    'ayar.cerezlerAciklama': 'Apaga cookies, armazenamento local e cache de todos os sites.',
    'ayar.veriTemizle': 'Limpar dados',
    'ayar.temizleniyor': 'Limpando…',
    'ayar.temizlendi': 'Limpo',
    'ayar.siteIzinleri': 'Permissões de sites',
    'ayar.siteIzinleriAciklama': 'Apaga escolhas lembradas de localização, câmera e notificações, e as exceções do bloqueador.',
    'ayar.izinSifirla': 'Redefinir permissões',
    'ayar.sifirlandi': 'Redefinido',
    'ayar.bolumVekil': 'Proxy',
    'ayar.vekil': 'Servidor proxy',
    'ayar.vekilAciklama': 'Tudo passa pelo proxy: navegação, listas de filtros e atualizações. Com um proxy ativo, o WebRTC não pode revelar o seu endereço real.',
    'ayar.vekilKapali': 'Desligado',
    'ayar.vekilSistem': 'Configuração do sistema',
    'ayar.vekilElle': 'Manual',
    'ayar.vekilAdres': 'Endereço',
    'ayar.vekilAdresAciklama': 'Por exemplo socks5://127.0.0.1:9050 (Tor) ou http://192.168.1.10:8080',
    'ayar.vekilAdresHatali': 'Esse endereço não foi aceito e não foi salvo. Formato: socks5://servidor:porta',
    'ayar.vekilReddedildi': 'O navegador não aceitou a regra de proxy, então as conexões apontam para um proxy inacessível. Verifique o endereço.',
    'ayar.vekilAtlaHatali': 'Algumas entradas não foram aceitas. Cada uma deve ser um domínio, *.exemplo.com ou 10.0.0.0/8.',
    'ayar.vekilAtla': 'Sites sem proxy',
    'ayar.vekilAtlaAciklama': 'Esses domínios se conectam diretamente. Endereços locais ficam sempre de fora.',
    'ayar.bolumListeler': 'Listas de filtros',
    'ayar.listeKullan': 'Usar listas baixadas',
    'ayar.listeKullanAciklama': 'Domínios de listas como a EasyList também são bloqueados. Desligado, vale apenas a lista integrada.',
    'ayar.otomatikGuncelle': 'Atualizar automaticamente',
    'ayar.otomatikGuncelleAciklama': 'As listas são renovadas em segundo plano no intervalo que declaram (geralmente a cada 4 dias).',
    'ayar.listeYenile': 'Renovar listas',
    'ayar.listeYenileAciklama': 'Baixa todas novamente agora.',
    'ayar.simdiGuncelle': 'Atualizar agora',
    'ayar.guncelleniyor': 'Atualizando…',
    'ayar.listeEkle': 'Adicione sua própria lista',
    'ayar.listeEkleAciklama': 'Um endereço https no formato Adblock Plus, hosts ou domínio simples.',
    'ayar.listeEkleIpucu': 'https://... endereço da lista',
    'ayar.ekle': 'Adicionar',
    'ayar.ekleniyor': 'Adicionando…',
    'ayar.listeKaldir': 'Remover',
    'ayar.listeIndirilmedi': 'Ainda não baixada',
    'ayar.listeHata': 'Falha ao atualizar: {hata}',
    'ayar.listeDurum': '{n} domínios · atualizada {ne}',
    'ayar.bugun': 'hoje',
    'ayar.dun': 'ontem',
    'ayar.gunOnce': 'há {n} dias',
    'ayar.bolumIzinler': 'Pedidos de permissão',
    'ayar.izinSor': 'Perguntar sempre',
    'ayar.izinVer': 'Sempre permitir',
    'ayar.izinRet': 'Sempre bloquear',
    'ayar.izinSatir': 'O que fazer quando um site pedir {izin}?',
    'ayar.bolumGorunum': 'Aparência',
    'ayar.yerImleriCubugu': 'Barra de favoritos',
    'ayar.yerImleriCubuguAciklama': 'Mostra os favoritos abaixo da barra de ferramentas.',
    'ayar.yenidenBaslat': 'Reinicie o Girginos Browser para aplicar o idioma.',

    'liste.easylist': 'Publicidade',
    'liste.easyprivacy': 'Rastreadores',
    'liste.hataHttps': 'Somente endereços https:// podem ser adicionados.',
    'liste.hataVar': 'Esta lista já foi adicionada.',
    /* --- site bilgisi menusu --- */
    'site.baglantiGuvenli': 'A conexão é segura',
    'site.baglantiGuvensiz': 'A conexão não é segura',
    'site.guvensizUyari': 'As informações inseridas nesta página são enviadas sem criptografia.',
    'site.sertifikaVeren': 'Emitido por: {ad}',
    'site.sertifikaSahip': 'Emitido para: {ad}',
    'site.sertifikaGecerlilik': 'Validade: {bas} – {bit}',
    'site.parmakIzi': 'Copiar impressão digital',
    'site.sertifikaYok': 'Sem informações do certificado',
    'site.cerezler': 'Cookies e dados do site',
    'site.cerezSayisi': '{n} cookies',
    'site.ucuncuTarafCerez': 'Permitir cookies de terceiros',
    'site.veriSil': 'Excluir os dados deste site',
    'site.engelleyici': 'Bloqueio de rastreadores',
    'site.izinSifirla': 'Redefinir permissões deste site',
    'site.ayarlar': 'Configurações do site',
    /* --- guncelleme --- */
    'menu.guncellemeDenetle': 'Verificar atualizações',
    'ayar.bolumGuncelleme': 'Atualizações',
    'ayar.surum': 'Versão',
    'ayar.guncellemeKontrolEt': 'Verificar agora',
    'ayar.guncellemeIndirDugme': 'Baixar',
    'ayar.guncellemeKur': 'Reiniciar e instalar',
    'ayar.guncellemeOtoKontrol': 'Verificar atualizações automaticamente',
    'ayar.guncellemeOtoKontrolAciklama': 'As informações de versão assinadas são verificadas na inicialização e a cada 6 horas.',
    'ayar.guncellemeOtoIndir': 'Baixar automaticamente',
    'ayar.guncellemeOtoIndirAciklama': 'A nova versão é baixada em segundo plano; a instalação ainda precisa da sua confirmação.',
    'ayar.guncellemeKanal': 'Canal de atualização',
    'ayar.guncellemeKanalAciklama': 'O canal beta recebe novidades mais cedo e é menos testado.',
    'ayar.kanalKararli': 'Estável',
    'ayar.kanalBeta': 'Beta',
    'guncelleme.kapali': 'Atualizações desativadas: nenhuma chave de publicação ou endereço configurado.',
    'guncelleme.paketlenmemis': 'Executando a partir do código-fonte; atualizações só se aplicam a uma versão instalada.',
    'guncelleme.bosta': 'Ainda não verificado.',
    'guncelleme.kontrol': 'Verificando…',
    'guncelleme.guncel': 'Você está na versão mais recente.',
    'guncelleme.bulundu': 'A versão {surum} está disponível.',
    'guncelleme.iniyor': 'Baixando… {n} %',
    'guncelleme.hazir': 'A versão {surum} está pronta para instalar.',
    'guncelleme.hata': 'Falha na verificação: {sebep}',
    /* --- yeni sekme ve hata sayfasi --- */
    'sayfa.tekrarDene': 'Tentar novamente',
    'sayfa.oneriYenile': 'Recarregue a página',
    'sayfa.oneriAdres': 'Verifique se há erros de digitação no endereço',
    'sayfa.oneriBaglanti': 'Verifique sua conexão com a internet',
    'sayfa.oneriBilgiGirme': 'Não insira informações sensíveis aqui',
    'hata.dns.baslik': 'Servidor não encontrado',
    'hata.dns.metin': 'Não foi possível resolver o IP deste endereço. O domínio pode estar incorreto ou fora do ar.',
    'hata.cevrimdisi.baslik': 'Sem conexão com a internet',
    'hata.cevrimdisi.metin': 'Seu dispositivo não parece estar conectado a uma rede.',
    'hata.baglanti.baslik': 'Não foi possível conectar',
    'hata.baglanti.metin': 'O servidor recusou a conexão ou ela caiu inesperadamente.',
    'hata.zamanAsimi.baslik': 'Tempo de conexão esgotado',
    'hata.zamanAsimi.metin': 'O servidor não respondeu em um tempo razoável.',
    'hata.sertifikaAd.baslik': 'O certificado não pertence a este site',
    'hata.sertifikaAd.metin': 'O domínio do certificado não corresponde ao endereço digitado.',
    'hata.sertifikaSure.baslik': 'O certificado expirou',
    'hata.sertifikaSure.metin': 'O certificado de segurança do servidor não é mais válido. Verifique também a data do dispositivo.',
    'hata.sertifikaMakam.baslik': 'Não foi possível verificar o certificado',
    'hata.sertifikaMakam.metin': 'A autoridade que assinou o certificado não é reconhecida. A conexão pode estar interceptada.',
    'hata.cokme.baslik': 'A aba parou de responder',
    'hata.cokme.metin': 'A página foi encerrada inesperadamente.',
    'hata.bilinmeyen.baslik': 'Não foi possível abrir esta página',
    'hata.bilinmeyen.metin': 'Ocorreu um problema desconhecido ao carregar a página.',
    'yenisekme.ara': 'Pesquisar',
    'yenisekme.sik': 'Sites frequentes',
    'yenisekme.oneCikan': 'Em destaque',
    'yenisekme.kisayolEkle': '+ Adicionar atalho',
    'yenisekme.kisayolIpucu': 'exemplo.com — pressione Enter para adicionar',
    'yenisekme.gecersizAdres': 'Digite um endereço válido',
    'yenisekme.kisayol': 'Atalho',
    'yenisekme.bosNot': 'Os sites que você mais visita aparecerão aqui.',
    'yenisekme.engellendi': 'O Girginos Browser bloqueou {n} solicitações de rastreadores até agora.',
    'yenisekme.engelleyiciAcik': 'O bloqueio de rastreadores está ativo. As solicitações bloqueadas serão contadas aqui.',
    /* --- adres onerileri --- */
    'oneri.ara': 'Pesquisar com {motor}',
    'oneri.adreseGit': 'Ir para o endereço',
    /* --- gorunum --- */
    'ayar.tema': 'Aparência',
    'ayar.temaAciklama': 'A interface, as páginas internas e os menus seguem esta escolha.',
    'ayar.temaSistem': 'Igual ao sistema',
    'ayar.temaAcik': 'Claro',
    'ayar.temaKoyu': 'Escuro',
    /* --- katman: izin kutusu --- */
    'dialog.izinIstiyor': 'solicita:',
    'izin.storage-access': 'acesso ao armazenamento',
    /* --- site izin duvari --- */
    'panel.siteIzinleri': 'Permissões do site',
    'izin.siteYok': 'Sem permissões para esta página.',
    'izin.durumSor': 'Perguntar',
    'izin.durumIzin': 'Permitir',
    'izin.durumRet': 'Bloquear',
    'izin.varsayilanEk': 'padrão',
    'izin.siteKarari': 'Definido por si para este site.',
    'izin.varsayilanIzleniyor': 'A aplicar o padrão global.',
    'izin.bilinmeyen': 'esta permissão ({ad})'
  }
};
