'use strict';

module.exports = {
  ad: 'Русский',
  yon: 'ltr',
  yerel: 'ru-RU',
  metin: {
    'menu.dosya': 'Файл',
    'menu.yeniSekme': 'Новая вкладка',
    'menu.sekmeyiKapat': 'Закрыть вкладку',
    'menu.adresCubugu': 'Перейти в адресную строку',
    'menu.sayfadaBul': 'Найти на странице',
    'menu.cikis': 'Выход',
    'menu.duzen': 'Правка',
    'menu.geriAl': 'Отменить',
    'menu.yinele': 'Повторить',
    'menu.kes': 'Вырезать',
    'menu.kopyala': 'Копировать',
    'menu.yapistir': 'Вставить',
    'menu.tumunuSec': 'Выделить всё',
    'menu.gorunum': 'Вид',
    'menu.yenile': 'Обновить',
    'menu.onbelleksizYenile': 'Обновить без кэша',
    'menu.yakinlastir': 'Увеличить',
    'menu.uzaklastir': 'Уменьшить',
    'menu.normalBoyut': 'Исходный размер',
    'menu.tamEkran': 'Полный экран',
    'menu.gelistirici': 'Инструменты разработчика',
    'menu.arayuzGelistirici': 'Инструменты разработчика интерфейса',
    'menu.gecmis': 'История',
    'menu.geri': 'Назад',
    'menu.ileri': 'Вперёд',
    'menu.gecmisiGoster': 'Показать историю',
    'menu.indirilenler': 'Загрузки',
    'menu.yerImleri': 'Закладки',
    'menu.yerImiEkle': 'Добавить страницу в закладки',
    'menu.yerImleriniGoster': 'Показать закладки',
    'menu.yerImleriCubugu': 'Панель закладок',
    'menu.sekmeler': 'Вкладки',
    'menu.sonrakiSekme': 'Следующая вкладка',
    'menu.oncekiSekme': 'Предыдущая вкладка',
    'menu.nSekme': 'Вкладка {n}',
    'menu.sonSekme': 'Последняя вкладка',
    'menu.yardim': 'Справка',
    'menu.ayarlar': 'Настройки',
    'menu.hakkinda': 'О программе Girginos Browser',
    'hakkinda.detay': 'Браузер с упором на приватность.',
    'menu.yazdir': 'Печать…',
    'menu.sayfayiKaydet': 'Сохранить страницу как…',
    'menu.digerAraclar': 'Дополнительные инструменты',
    'menu.yakinlastirma': 'Масштаб',
    'menu.veriSil': 'Удалить данные о просмотре…',
    'arac.menu': 'Меню',

    'baglam.baglantiYeniSekme': 'Открыть ссылку в новой вкладке',
    'baglam.baglantiKopyala': 'Копировать адрес ссылки',
    'baglam.gorselYeniSekme': 'Открыть изображение в новой вкладке',
    'baglam.gorselKopyala': 'Копировать адрес изображения',
    'baglam.gorselKaydet': 'Сохранить изображение',
    'baglam.ara': 'Искать «{q}»',
    'baglam.kaynak': 'Посмотреть исходный код',
    'baglam.incele': 'Исследовать элемент',

    'dialog.iptal': 'Отмена',
    'dialog.ac': 'Открыть',
    'dialog.disBaslik': 'Выход из Girginos Browser',
    'dialog.disMesaj': 'Ссылка «{sema}» будет открыта в другом приложении.',
    'dialog.reddet': 'Запретить',
    'dialog.izinVer': 'Разрешить',
    'dialog.izinBaslik': 'Запрос разрешения',
    'dialog.izinMesaj': '{origin} запрашивает:',
    'dialog.izinHatirla': 'Запомнить мой выбор для этого сайта',
    'dialog.calistirBaslik': 'Это исполняемый файл',
    'dialog.calistirMesaj': 'Этот файл может навредить вашему компьютеру.',
    'dialog.calistirDevam': 'Всё равно запустить',
    'dialog.kaynak': 'Источник',

    'izin.notifications': 'уведомления',
    'izin.geolocation': 'ваше местоположение',
    'izin.media': 'камеру и микрофон',
    'izin.midi': 'MIDI-устройства',
    'izin.midiSysex': 'MIDI-устройства',
    'izin.clipboard-read': 'чтение буфера обмена',
    'izin.display-capture': 'демонстрацию экрана',
    'izin.openExternal': 'открытие другого приложения',
    'izin.idle-detection': 'определение бездействия',
    'izin.pointerLock': 'захват курсора мыши',
    'izin.fullscreen': 'полноэкранный режим',

    'arac.geri': 'Назад',
    'arac.ileri': 'Вперёд',
    'arac.yenile': 'Обновить',
    'arac.durdur': 'Остановить',
    'arac.anasayfa': 'Домой',
    'arac.yeniSekme': 'Новая вкладка',
    'arac.sekmeyiKapat': 'Закрыть вкладку',
    'arac.gecmis': 'История',
    'arac.indirilenler': 'Загрузки',
    'arac.ayarlar': 'Настройки',
    'arac.adresIpucu': 'Поиск или адрес',
    'arac.yerImiEkle': 'Добавить закладку',
    'arac.yerImiCikar': 'Удалить закладку',
    'arac.kalkanAcik': 'Заблокировано трекеров: {n} — нажмите, чтобы отключить',
    'arac.kalkanKapali': 'Блокировка на этом сайте выключена — нажмите, чтобы включить',
    'arac.guvenli': 'Соединение зашифровано (HTTPS)',
    'arac.guvensiz': 'Соединение не зашифровано',
    'arac.yeniSekmeBaslik': 'Новая вкладка',
    'arac.adsiz': 'Без названия',

    'bul.ipucu': 'Найти на странице',
    'bul.onceki': 'Предыдущее',
    'bul.sonraki': 'Следующее',
    'bul.kapat': 'Закрыть',

    'panel.gecmis': 'История',
    'panel.yerImleri': 'Закладки',
    'panel.indirilenler': 'Загрузки',
    'panel.ayarlar': 'Настройки',
    'panel.kapat': 'Закрыть панель',
    'panel.kaldir': 'Удалить',
    'gecmis.ara': 'Поиск в истории',
    'gecmis.temizle': 'Очистить историю',
    'gecmis.bos': 'История пуста.',
    'gecmis.eslesmeYok': 'Совпадений нет.',
    'gecmis.bugun': 'Сегодня',
    'gecmis.dun': 'Вчера',
    'yerimi.bos': 'У вас пока нет закладок.',
    'yerimi.cubukBos': 'Закладок нет — нажмите Ctrl+D, чтобы добавить страницу',
    'yerimi.tumu': 'Все закладки',
    'yerimi.ac': 'Открыть',
    'yerimi.yeniSekmedeAc': 'Открыть в новой вкладке',
    'yerimi.adresiKopyala': 'Копировать адрес',
    'yerimi.duzenle': 'Переименовать…',
    'yerimi.cubuguGizle': 'Скрыть панель закладок',

    'indirme.bos': 'Загрузок пока нет.',
    'indirme.devam': 'Загружается',
    'indirme.tamam': 'Завершено',
    'indirme.iptal': 'Отменено',
    'indirme.hata': 'Не удалось',
    'indirme.kesildi': 'Прервано',
    'indirme.ac': 'Открыть',
    'indirme.klasor': 'Показать в папке',
    'indirme.tumunuGoster': 'Показать все',

    'ayar.engellenenSayi': 'Заблокировано трекеров',
    'ayar.yukluAlan': 'Доменов загружено из списков',
    'ayar.yerImiSayi': 'Закладок',
    'ayar.bolumArama': 'Поиск и запуск',
    'ayar.dil': 'Язык',
    'ayar.dilAciklama': 'Меню, панели и страницы ошибок используют этот язык.',
    'ayar.dilSistem': 'Язык системы',
    'ayar.aramaMotoru': 'Поисковая система',
    'ayar.aramaMotoruAciklama': 'Запросы из адресной строки уходят сюда.',
    'ayar.anasayfa': 'Домашняя страница',
    'ayar.anasayfaAciklama': 'Адрес, который открывает кнопка «Домой».',
    'ayar.anasayfaIpucu': 'Оставьте пустым для страницы новой вкладки',
    'ayar.bolumGizlilik': 'Приватность',
    'ayar.engelleyici': 'Блокировщик трекеров и рекламы',
    'ayar.engelleyiciAciklama': 'Отменяет запросы к известным рекламным и отслеживающим доменам.',
    'ayar.dnt': 'Отправлять сигнал «не отслеживать»',
    'ayar.dntAciklama': 'Добавляет заголовки DNT и Sec-GPC к каждому запросу.',
    'ayar.gecmisiKaydet': 'Сохранять историю',
    'ayar.gecmisiKaydetAciklama': 'Когда выключено, посещённые страницы не пишутся на диск.',
    'ayar.cerezler': 'Куки и кэш',
    'ayar.cerezlerAciklama': 'Удаляет куки, локальное хранилище и кэш всех сайтов.',
    'ayar.veriTemizle': 'Очистить данные',
    'ayar.temizleniyor': 'Очистка…',
    'ayar.temizlendi': 'Очищено',
    'ayar.siteIzinleri': 'Разрешения сайтов',
    'ayar.siteIzinleriAciklama': 'Удаляет сохранённые решения по геопозиции, камере и уведомлениям, а также исключения блокировщика.',
    'ayar.izinSifirla': 'Сбросить разрешения',
    'ayar.sifirlandi': 'Сброшено',
    'ayar.bolumListeler': 'Списки фильтров',
    'ayar.listeKullan': 'Использовать загруженные списки',
    'ayar.listeKullanAciklama': 'Домены из списков вроде EasyList тоже блокируются. Если выключено, работает только встроенный список.',
    'ayar.otomatikGuncelle': 'Обновлять автоматически',
    'ayar.otomatikGuncelleAciklama': 'Списки обновляются в фоне с заявленной периодичностью (обычно раз в 4 дня).',
    'ayar.listeYenile': 'Обновить списки',
    'ayar.listeYenileAciklama': 'Немедленно загружает все заново.',
    'ayar.simdiGuncelle': 'Обновить сейчас',
    'ayar.guncelleniyor': 'Обновление…',
    'ayar.listeEkle': 'Добавить свой список',
    'ayar.listeEkleAciklama': 'Адрес https в формате Adblock Plus, hosts или простого списка доменов.',
    'ayar.listeEkleIpucu': 'https://... адрес списка фильтров',
    'ayar.ekle': 'Добавить',
    'ayar.ekleniyor': 'Добавление…',
    'ayar.listeKaldir': 'Удалить',
    'ayar.listeIndirilmedi': 'Ещё не загружен',
    'ayar.listeHata': 'Не удалось обновить: {hata}',
    'ayar.listeDurum': 'доменов: {n} · обновлён {ne}',
    'ayar.bugun': 'сегодня',
    'ayar.dun': 'вчера',
    'ayar.gunOnce': '{n} дн. назад',
    'ayar.bolumIzinler': 'Запросы разрешений',
    'ayar.izinSor': 'Спрашивать каждый раз',
    'ayar.izinVer': 'Всегда разрешать',
    'ayar.izinRet': 'Всегда запрещать',
    'ayar.izinSatir': 'Что делать, когда сайт запрашивает {izin}?',
    'ayar.bolumGorunum': 'Оформление',
    'ayar.yerImleriCubugu': 'Панель закладок',
    'ayar.yerImleriCubuguAciklama': 'Показывает закладки под панелью инструментов.',
    'ayar.yenidenBaslat': 'Перезапустите Girginos Browser, чтобы применить язык.',

    'liste.easylist': 'Реклама',
    'liste.easyprivacy': 'Трекеры',
    'liste.hataHttps': 'Можно добавлять только адреса https://.',
    'liste.hataVar': 'Этот список уже добавлен.',
    /* --- site bilgisi menusu --- */
    'site.baglantiGuvenli': 'Соединение защищено',
    'site.baglantiGuvensiz': 'Соединение не защищено',
    'site.guvensizUyari': 'Данные, введённые на этой странице, передаются без шифрования.',
    'site.sertifikaVeren': 'Кем выдан: {ad}',
    'site.sertifikaSahip': 'Кому выдан: {ad}',
    'site.sertifikaGecerlilik': 'Срок действия: {bas} – {bit}',
    'site.parmakIzi': 'Копировать отпечаток',
    'site.sertifikaYok': 'Нет данных о сертификате',
    'site.cerezler': 'Файлы cookie и данные сайта',
    'site.cerezSayisi': 'Файлов cookie: {n}',
    'site.veriSil': 'Удалить данные этого сайта',
    'site.engelleyici': 'Блокировка трекеров',
    'site.izinSifirla': 'Сбросить разрешения этого сайта',
    'site.ayarlar': 'Настройки сайта',
    /* --- guncelleme --- */
    'menu.guncellemeDenetle': 'Проверить обновления',
    'ayar.bolumGuncelleme': 'Обновления',
    'ayar.surum': 'Версия',
    'ayar.guncellemeKontrolEt': 'Проверить сейчас',
    'ayar.guncellemeIndirDugme': 'Загрузить',
    'ayar.guncellemeKur': 'Перезапустить и установить',
    'ayar.guncellemeOtoKontrol': 'Проверять обновления автоматически',
    'ayar.guncellemeOtoKontrolAciklama': 'Подписанные сведения о выпуске проверяются при запуске и каждые 6 часов.',
    'ayar.guncellemeOtoIndir': 'Загружать автоматически',
    'ayar.guncellemeOtoIndirAciklama': 'Новая версия загружается в фоне; установка по-прежнему требует вашего подтверждения.',
    'ayar.guncellemeKanal': 'Канал обновлений',
    'ayar.guncellemeKanalAciklama': 'Бета-канал получает новинки раньше и менее протестирован.',
    'ayar.kanalKararli': 'Стабильный',
    'ayar.kanalBeta': 'Бета',
    'guncelleme.kapali': 'Обновления отключены: не задан ключ выпуска или адрес.',
    'guncelleme.paketlenmemis': 'Запуск из исходников; обновления применимы только к установленной сборке.',
    'guncelleme.bosta': 'Ещё не проверялось.',
    'guncelleme.kontrol': 'Проверка…',
    'guncelleme.guncel': 'У вас последняя версия.',
    'guncelleme.bulundu': 'Доступна версия {surum}.',
    'guncelleme.iniyor': 'Загрузка… {n} %',
    'guncelleme.hazir': 'Версия {surum} готова к установке.',
    'guncelleme.hata': 'Не удалось проверить: {sebep}',
    /* --- yeni sekme ve hata sayfasi --- */
    'sayfa.tekrarDene': 'Повторить',
    'sayfa.oneriYenile': 'Обновите страницу',
    'sayfa.oneriAdres': 'Проверьте адрес на опечатки',
    'sayfa.oneriBaglanti': 'Проверьте интернет-соединение',
    'sayfa.oneriBilgiGirme': 'Не вводите здесь конфиденциальные данные',
    'hata.dns.baslik': 'Сервер не найден',
    'hata.dns.metin': 'Не удалось определить IP-адрес. Домен может быть написан с ошибкой или не работать.',
    'hata.cevrimdisi.baslik': 'Нет подключения к интернету',
    'hata.cevrimdisi.metin': 'Похоже, устройство не подключено к сети.',
    'hata.baglanti.baslik': 'Не удалось подключиться',
    'hata.baglanti.metin': 'Сервер отклонил соединение либо оно неожиданно прервалось.',
    'hata.zamanAsimi.baslik': 'Время ожидания истекло',
    'hata.zamanAsimi.metin': 'Сервер не ответил за разумное время.',
    'hata.sertifikaAd.baslik': 'Сертификат не принадлежит этому сайту',
    'hata.sertifikaAd.metin': 'Домен в сертификате сервера не совпадает с введённым адресом.',
    'hata.sertifikaSure.baslik': 'Срок действия сертификата истёк',
    'hata.sertifikaSure.metin': 'Сертификат безопасности сервера больше не действителен. Проверьте также дату на устройстве.',
    'hata.sertifikaMakam.baslik': 'Не удалось проверить сертификат',
    'hata.sertifikaMakam.metin': 'Центр, подписавший сертификат, не распознан. Соединение может быть перехвачено.',
    'hata.cokme.baslik': 'Вкладка перестала отвечать',
    'hata.cokme.metin': 'Страница неожиданно закрылась.',
    'hata.bilinmeyen.baslik': 'Не удалось открыть страницу',
    'hata.bilinmeyen.metin': 'При загрузке страницы произошла неизвестная ошибка.',
    'yenisekme.ara': 'Поиск',
    'yenisekme.sik': 'Часто посещаемые',
    'yenisekme.oneCikan': 'Рекомендуем',
    'yenisekme.kisayolEkle': '+ Добавить ярлык',
    'yenisekme.kisayolIpucu': 'primer.ru — нажмите Enter, чтобы добавить',
    'yenisekme.gecersizAdres': 'Введите корректный адрес',
    'yenisekme.kisayol': 'Ярлык',
    'yenisekme.bosNot': 'Здесь появятся сайты, которые вы посещаете чаще всего.',
    'yenisekme.engellendi': 'Girginos Browser заблокировал {n} запросов трекеров.',
    'yenisekme.engelleyiciAcik': 'Блокировка трекеров включена. Заблокированные запросы будут подсчитываться здесь.',
    /* --- adres onerileri --- */
    'oneri.ara': 'Искать в {motor}',
    'oneri.adreseGit': 'Перейти по адресу',
    /* --- gorunum --- */
    'ayar.tema': 'Оформление',
    'ayar.temaAciklama': 'Интерфейс, встроенные страницы и меню следуют этому выбору.',
    'ayar.temaSistem': 'Как в системе',
    'ayar.temaAcik': 'Светлое',
    'ayar.temaKoyu': 'Тёмное',
    /* --- katman: izin kutusu --- */
    'dialog.izinIstiyor': 'запрашивает:',
    'izin.storage-access': 'доступ к хранилищу',
    /* --- site izin duvari --- */
    'panel.siteIzinleri': 'Разрешения сайта',
    'izin.siteYok': 'Для этой страницы нет разрешений.',
    'izin.durumSor': 'Спрашивать',
    'izin.durumIzin': 'Разрешить',
    'izin.durumRet': 'Блокировать',
    'izin.varsayilanEk': 'по умолчанию',
    'izin.siteKarari': 'Вы задали это для сайта.',
    'izin.varsayilanIzleniyor': 'Применяется общее значение.'
  }
};
