'use strict';

// Referans dil. Diğer dosyalar bu anahtar kümesini birebir taşımak zorunda;
// test/sozlesme.js eksik ya da fazla anahtarı yakalar.

module.exports = {
  ad: 'Türkçe',
  yon: 'ltr',
  yerel: 'tr-TR',
  metin: {
    /* --- uygulama menüsü --- */
    'menu.dosya': 'Dosya',
    'menu.yeniSekme': 'Yeni sekme',
    'menu.sekmeyiKapat': 'Sekmeyi kapat',
    'menu.adresCubugu': 'Adres çubuğuna git',
    'menu.sayfadaBul': 'Sayfada bul',
    'menu.cikis': 'Çıkış',
    'menu.duzen': 'Düzen',
    'menu.geriAl': 'Geri al',
    'menu.yinele': 'Yinele',
    'menu.kes': 'Kes',
    'menu.kopyala': 'Kopyala',
    'menu.yapistir': 'Yapıştır',
    'menu.tumunuSec': 'Tümünü seç',
    'menu.gorunum': 'Görünüm',
    'menu.yenile': 'Yenile',
    'menu.onbelleksizYenile': 'Önbelleği yoksayarak yenile',
    'menu.yakinlastir': 'Yakınlaştır',
    'menu.uzaklastir': 'Uzaklaştır',
    'menu.normalBoyut': 'Normal boyut',
    'menu.tamEkran': 'Tam ekran',
    'menu.gelistirici': 'Geliştirici araçları',
    'menu.arayuzGelistirici': 'Arayüz geliştirici araçları',
    'menu.gecmis': 'Geçmiş',
    'menu.geri': 'Geri',
    'menu.ileri': 'İleri',
    'menu.gecmisiGoster': 'Geçmişi göster',
    'menu.indirilenler': 'İndirilenler',
    'menu.yerImleri': 'Yer imleri',
    'menu.yerImiEkle': 'Bu sayfayı yer imlerine ekle',
    'menu.yerImleriniGoster': 'Yer imlerini göster',
    'menu.yerImleriCubugu': 'Yer imleri çubuğu',
    'menu.sekmeler': 'Sekmeler',
    'menu.sonrakiSekme': 'Sonraki sekme',
    'menu.oncekiSekme': 'Önceki sekme',
    'menu.nSekme': '{n}. sekme',
    'menu.sonSekme': 'Son sekme',
    'menu.yardim': 'Yardım',
    'menu.ayarlar': 'Ayarlar',
    'menu.hakkinda': 'Girginos Browser hakkında',
    'hakkinda.detay': 'Gizlilik odaklı tarayıcı.',
    'menu.yazdir': 'Yazdır…',
    'menu.sayfayiKaydet': 'Sayfayı farklı kaydet…',
    'menu.digerAraclar': 'Diğer araçlar',
    'menu.yakinlastirma': 'Yakınlaştırma',
    'menu.veriSil': 'Tarama verilerini sil…',
    'arac.onbellek': 'Önbelleği sıfırla',
    'arac.onbellekTemizlendi': 'Önbellek sıfırlandı, sayfa yenilendi',
    'arac.onbellekHata': 'Önbellek sıfırlanamadı',
    'arac.menu': 'Menü',

    /* --- bağlam menüsü --- */
    'baglam.baglantiYeniSekme': 'Bağlantıyı yeni sekmede aç',
    'baglam.baglantiKopyala': 'Bağlantı adresini kopyala',
    'baglam.gorselYeniSekme': 'Görseli yeni sekmede aç',
    'baglam.gorselKopyala': 'Görsel adresini kopyala',
    'baglam.gorselKaydet': 'Görseli kaydet',
    'baglam.ara': '"{q}" ifadesini ara',
    'baglam.kaynak': 'Sayfa kaynağını görüntüle',
    'baglam.incele': 'Öğeyi incele',

    /* --- iletişim kutuları --- */
    'dialog.iptal': 'İptal',
    'dialog.ac': 'Aç',
    'dialog.disBaslik': 'Girginos Browser dışına çık',
    'dialog.disMesaj': '"{sema}" bağlantısı başka bir uygulamada açılacak.',
    'dialog.reddet': 'Reddet',
    'dialog.izinVer': 'İzin ver',
    'dialog.izinBaslik': 'İzin isteği',
    'dialog.izinMesaj': '{origin} şunu istiyor:',
    'dialog.izinHatirla': 'Bu site için kararımı hatırla',
    'dialog.calistirBaslik': 'Bu dosya çalıştırılabilir',
    'dialog.calistirMesaj': 'Bu dosya bilgisayarınıza zarar verebilir.',
    'dialog.calistirDevam': 'Yine de çalıştır',
    'dialog.kaynak': 'Kaynak',

    /* --- izin adları --- */
    'izin.notifications': 'bildirim gönderme',
    'izin.geolocation': 'konum bilgisi',
    'izin.media': 'kamera ve mikrofon',
    'izin.midi': 'MIDI aygıtları',
    'izin.midiSysex': 'MIDI aygıtları',
    'izin.clipboard-read': 'pano okuma',
    'izin.display-capture': 'ekran paylaşımı',
    'izin.openExternal': 'başka bir uygulamayı açma',
    'izin.idle-detection': 'boşta kalma algılama',
    'izin.pointerLock': 'fare imlecini yakalama',
    'izin.fullscreen': 'tam ekrana geçme',

    /* --- araç çubuğu --- */
    'arac.geri': 'Geri',
    'arac.ileri': 'İleri',
    'arac.yenile': 'Yenile',
    'arac.durdur': 'Durdur',
    'arac.anasayfa': 'Anasayfa',
    'arac.yeniSekme': 'Yeni sekme',
    'arac.sekmeyiKapat': 'Sekmeyi kapat',
    'arac.gecmis': 'Geçmiş',
    'arac.indirilenler': 'İndirilenler',
    'arac.ayarlar': 'Ayarlar',
    'arac.adresIpucu': 'Ara ya da adres yaz',
    'arac.yerImiEkle': 'Yer imlerine ekle',
    'arac.yerImiCikar': 'Yer imlerinden çıkar',
    'arac.kalkanAcik': '{n} izleyici engellendi — kapatmak için tıkla',
    'arac.kalkanKapali': 'Bu sitede engelleyici kapalı — açmak için tıkla',
    'arac.reklamEngel': 'Reklam engelleyici',
    'arac.reklamEngelAcik': 'Reklam engelleyici açık (tüm siteler) — kapatmak için tıkla',
    'arac.reklamEngelKapali': 'Reklam engelleyici kapalı (tüm siteler) — açmak için tıkla',
    'arac.guvenli': 'Bağlantı şifreli (HTTPS)',
    'arac.guvensiz': 'Bağlantı şifresiz',
    'arac.yeniSekmeBaslik': 'Yeni sekme',
    'arac.adsiz': 'Adsız',

    /* --- sayfada bul --- */
    'bul.ipucu': 'Sayfada bul',
    'bul.onceki': 'Önceki',
    'bul.sonraki': 'Sonraki',
    'bul.kapat': 'Kapat',

    /* --- paneller --- */
    'panel.gecmis': 'Geçmiş',
    'panel.yerImleri': 'Yer imleri',
    'panel.indirilenler': 'İndirilenler',
    'panel.ayarlar': 'Ayarlar',
    'panel.kapat': 'Paneli kapat',
    'panel.kaldir': 'Kaldır',
    'gecmis.ara': 'Geçmişte ara',
    'gecmis.temizle': 'Geçmişi temizle',
    'gecmis.bos': 'Geçmiş boş.',
    'gecmis.eslesmeYok': 'Eşleşen kayıt yok.',
    'gecmis.bugun': 'Bugün',
    'gecmis.dun': 'Dün',
    'yerimi.bos': 'Henüz yer imi eklemediniz.',
    'yerimi.cubukBos': 'Yer imi yok — bir sayfayı eklemek için Ctrl+D',
    'yerimi.tumu': 'Tüm yer imleri',
    'yerimi.ac': 'Aç',
    'yerimi.yeniSekmedeAc': 'Yeni sekmede aç',
    'yerimi.adresiKopyala': 'Adresi kopyala',
    'yerimi.duzenle': 'Adını düzenle…',
    'yerimi.cubuguGizle': 'Yer imleri çubuğunu gizle',

    /* --- indirilenler --- */
    'indirme.bos': 'Henüz bir dosya indirilmedi.',
    'indirme.devam': 'İndiriliyor',
    'indirme.tamam': 'Tamamlandı',
    'indirme.iptal': 'İptal edildi',
    'indirme.hata': 'Başarısız',
    'indirme.kesildi': 'Kesildi',
    'indirme.ac': 'Aç',
    'indirme.klasor': 'Klasörde göster',
    'indirme.tumunuGoster': 'Tümünü göster',

    /* --- ayarlar --- */
    'ayar.engellenenSayi': 'Şimdiye kadar engellenen izleyici',
    'ayar.yukluAlan': 'Listelerden yüklü alan adı',
    'ayar.yerImiSayi': 'Yer imi',
    'ayar.bolumArama': 'Arama ve başlangıç',
    'ayar.dil': 'Dil',
    'ayar.dilAciklama': 'Menüler, paneller ve hata sayfaları bu dilde gösterilir.',
    'ayar.dilSistem': 'Sistem dili',
    'ayar.aramaMotoru': 'Arama motoru',
    'ayar.aramaMotoruAciklama': 'Adres çubuğuna yazdığınız aramalar buraya gider.',
    'ayar.anasayfa': 'Anasayfa',
    'ayar.anasayfaAciklama': 'Anasayfa düğmesinin açacağı adres.',
    'ayar.anasayfaIpucu': 'Boş bırakırsanız yeni sekme sayfası',
    'ayar.bolumGizlilik': 'Gizlilik',
    'ayar.engelleyici': 'İzleyici ve reklam engelleyici',
    'ayar.engelleyiciAciklama': 'Bilinen reklam ve izleme alan adlarına giden istekleri keser.',
    'ayar.dnt': 'Takip etme sinyali gönder',
    'ayar.dntAciklama': 'Her isteğe DNT ve Sec-GPC başlıklarını ekler.',
    'ayar.ucuncuTarafCerez': 'Üçüncü taraf çerezleri engelle',
    'ayar.ucuncuTarafCerezAciklama': 'Siteler arası takibin ana taşıyıcısı. Bir site bozulursa adres çubuğundaki kilit menüsünden o siteye izin verebilirsiniz. Bu ayarı değiştirmek tam olarak yeniden başlattığınızda geçerli olur.',
    'ayar.kapanistaCerezSil': 'Kapanışta çerezleri sil',
    'ayar.kapanistaCerezSilAciklama': 'Yer imlerinizdeki sitelerin çerezleri korunur, oturumunuz orada açık kalır.',
    'ayar.gecmisiKaydet': 'Geçmişi kaydet',
    'ayar.gecmisiKaydetAciklama': 'Kapalıyken ziyaret ettiğiniz sayfalar diske yazılmaz.',
    'ayar.cerezler': 'Çerezler ve önbellek',
    'ayar.cerezlerAciklama': 'Tüm sitelerin çerezlerini, yerel depolarını ve önbelleğini siler.',
    'ayar.veriTemizle': 'Verileri temizle',
    'ayar.temizleniyor': 'Temizleniyor…',
    'ayar.temizlendi': 'Temizlendi',
    'ayar.siteIzinleri': 'Site izinleri',
    'ayar.siteIzinleriAciklama': 'Konum, kamera, bildirim gibi hatırlanan kararları ve engelleyici istisnalarını siler.',
    'ayar.izinSifirla': 'Site izinlerini sıfırla',
    'ayar.sifirlandi': 'Sıfırlandı',
    'ayar.bolumVekil': 'Vekil sunucu',
    'ayar.vekil': 'Vekil sunucu',
    'ayar.vekilAciklama': 'Gezinme, filtre listeleri ve güncelleme dahil bütün bağlantılar vekilden geçer. Vekil açıkken WebRTC gerçek adresinizi yayınlayamaz.',
    'ayar.vekilKapali': 'Kapalı',
    'ayar.vekilSistem': 'Sistem ayarı',
    'ayar.vekilElle': 'Elle',
    'ayar.vekilAdres': 'Adres',
    'ayar.vekilAdresAciklama': 'Örnek: socks5://127.0.0.1:9050 (Tor) ya da http://192.168.1.10:8080',
    'ayar.vekilAdresHatali': 'Bu adres kabul edilmedi, kaydedilmedi. Biçim: socks5://sunucu:port',
    'ayar.vekilReddedildi': 'Vekil kuralı tarayıcı tarafından kabul edilmedi; bağlantılar erişilemeyen bir vekile yönlendirildi. Adresi kontrol edin.',
    'ayar.vekilAtlaHatali': 'Listedeki bazı girdiler kabul edilmedi. Her satır bir alan adı, *.alan.com ya da 10.0.0.0/8 biçiminde olmalı.',
    'ayar.vekilAtla': 'Vekilsiz adresler',
    'ayar.vekilAtlaAciklama': 'Bu alan adları vekile uğramadan doğrudan bağlanır. Yerel adresler her zaman hariçtir.',
    'ayar.bolumListeler': 'Filtre listeleri',
    'ayar.listeKullan': 'İndirilen listeleri kullan',
    'ayar.listeKullanAciklama': 'EasyList gibi listelerdeki alan adları da engellenir. Kapalıyken yalnızca yerleşik liste çalışır.',
    'ayar.otomatikGuncelle': 'Otomatik güncelle',
    'ayar.otomatikGuncelleAciklama': 'Listeler kendi belirttiği sıklıkta (genellikle 4 günde bir) arka planda yenilenir.',
    'ayar.listeYenile': 'Listeleri yenile',
    'ayar.listeYenileAciklama': 'Beklemeden hepsini yeniden indirir.',
    'ayar.simdiGuncelle': 'Şimdi güncelle',
    'ayar.guncelleniyor': 'Güncelleniyor…',
    'ayar.listeEkle': 'Kendi listeni ekle',
    'ayar.listeEkleAciklama': 'Adblock Plus, hosts ya da düz alan adı biçiminde https bir adres.',
    'ayar.listeEkleIpucu': 'https://... filtre listesi adresi',
    'ayar.ekle': 'Ekle',
    'ayar.ekleniyor': 'Ekleniyor…',
    'ayar.listeKaldir': 'Kaldır',
    'ayar.listeIndirilmedi': 'Henüz indirilmedi',
    'ayar.listeHata': 'Güncellenemedi: {hata}',
    'ayar.listeDurum': '{n} alan adı · {ne} güncellendi',
    'ayar.bugun': 'bugün',
    'ayar.dun': 'dün',
    'ayar.gunOnce': '{n} gün önce',
    'ayar.bolumIzinler': 'İzin istekleri',
    'ayar.izinSor': 'Her seferinde sor',
    'ayar.izinVer': 'Otomatik izin ver',
    'ayar.izinRet': 'Otomatik reddet',
    'ayar.izinSatir': 'Bir site {izin} istediğinde ne yapılsın?',
    'ayar.bolumGorunum': 'Görünüm',
    'ayar.yerImleriCubugu': 'Yer imleri çubuğu',
    'ayar.yerImleriCubuguAciklama': 'Araç çubuğunun altında yer imlerini gösterir.',
    'ayar.yenidenBaslat': 'Dil değişikliği için Girginos Browser yeniden başlatılmalı.',

    /* --- liste açıklamaları --- */
    'liste.easylist': 'Reklamlar',
    'liste.easyprivacy': 'İzleyiciler',
    'liste.hataHttps': 'Yalnızca https:// adresleri eklenebilir.',
    'liste.hataVar': 'Bu liste zaten ekli.',
    /* --- site bilgisi menusu --- */
    'site.baglantiGuvenli': 'Bağlantı güvenli',
    'site.baglantiGuvensiz': 'Bağlantı şifresiz',
    'site.guvensizUyari': 'Bu sayfaya girdiğiniz bilgiler şifrelenmeden gönderilir.',
    'site.sertifikaVeren': 'Veren: {ad}',
    'site.sertifikaSahip': 'Sahibi: {ad}',
    'site.sertifikaGecerlilik': 'Geçerlilik: {bas} – {bit}',
    'site.parmakIzi': 'Parmak izini kopyala',
    'site.sertifikaYok': 'Sertifika bilgisi yok',
    'site.cerezler': 'Çerezler ve site verileri',
    'site.cerezSayisi': '{n} çerez',
    'site.ucuncuTarafCerez': 'Üçüncü taraf çerezlere izin ver',
    'site.veriSil': 'Bu sitenin verilerini sil',
    'site.engelleyici': 'İzleyici engelleyici',
    'site.izinSifirla': 'Bu site için izinleri sıfırla',
    'site.ayarlar': 'Site ayarları',
    /* --- guncelleme --- */
    'menu.guncellemeDenetle': 'Güncellemeleri denetle',
    'ayar.bolumGuncelleme': 'Güncelleme',
    'ayar.surum': 'Sürüm',
    'ayar.guncellemeKontrolEt': 'Şimdi denetle',
    'ayar.guncellemeIndirDugme': 'İndir',
    'ayar.guncellemeKur': 'Yeniden başlat ve kur',
    'ayar.guncellemeOtoKontrol': 'Güncellemeleri otomatik denetle',
    'ayar.guncellemeOtoKontrolAciklama': 'Açılışta ve 6 saatte bir imzalı sürüm bilgisi kontrol edilir.',
    'ayar.guncellemeOtoIndir': 'Otomatik indir',
    'ayar.guncellemeOtoIndirAciklama': 'Yeni sürüm bulununca arka planda indirilir; kurulum yine sizin onayınızla yapılır.',
    'ayar.guncellemeKanal': 'Güncelleme kanalı',
    'ayar.guncellemeKanalAciklama': 'Beta kanalı yeni özellikleri erken alır, daha az test edilmiştir.',
    'ayar.kanalKararli': 'Kararlı',
    'ayar.kanalBeta': 'Beta',
    'guncelleme.kapali': 'Güncelleme kapalı: yayın anahtarı ya da adresi tanımlı değil.',
    'guncelleme.paketlenmemis': 'Kaynaktan çalışıyor; güncelleme yalnızca kurulu sürümde uygulanır.',
    'guncelleme.bosta': 'Henüz denetlenmedi.',
    'guncelleme.kontrol': 'Denetleniyor…',
    'guncelleme.guncel': 'En güncel sürümü kullanıyorsunuz.',
    'guncelleme.bulundu': '{surum} sürümü yayınlandı.',
    'guncelleme.iniyor': 'İndiriliyor… %{n}',
    'guncelleme.hazir': '{surum} kuruluma hazır.',
    'guncelleme.hata': 'Denetlenemedi: {sebep}',
    /* --- yeni sekme ve hata sayfasi --- */
    'sayfa.tekrarDene': 'Tekrar dene',
    'sayfa.oneriYenile': 'Sayfayı yenileyin',
    'sayfa.oneriAdres': 'Adresi yazım hatasına karşı kontrol edin',
    'sayfa.oneriBaglanti': 'İnternet bağlantınızı kontrol edin',
    'sayfa.oneriBilgiGirme': 'Bu sayfaya hassas bilgi girmeyin',
    'hata.dns.baslik': 'Sunucu bulunamadı',
    'hata.dns.metin': 'Bu adresin IP karşılığı çözülemedi. Alan adı yanlış yazılmış ya da yayında olmayabilir.',
    'hata.cevrimdisi.baslik': 'İnternet bağlantısı yok',
    'hata.cevrimdisi.metin': 'Cihazınız şu anda ağa bağlı görünmüyor.',
    'hata.baglanti.baslik': 'Bağlantı kurulamadı',
    'hata.baglanti.metin': 'Sunucu bağlantıyı kabul etmedi ya da bağlantı beklenmedik şekilde kesildi.',
    'hata.zamanAsimi.baslik': 'Bağlantı zaman aşımına uğradı',
    'hata.zamanAsimi.metin': 'Sunucu makul bir sürede yanıt vermedi.',
    'hata.sertifikaAd.baslik': 'Sertifika bu siteye ait değil',
    'hata.sertifikaAd.metin': 'Sunucunun sertifikasındaki alan adı, girdiğiniz adresle uyuşmuyor.',
    'hata.sertifikaSure.baslik': 'Sertifikanın süresi geçmiş',
    'hata.sertifikaSure.metin': 'Sunucunun güvenlik sertifikası artık geçerli değil. Cihazınızın tarihini de kontrol edin.',
    'hata.sertifikaMakam.baslik': 'Sertifika doğrulanamadı',
    'hata.sertifikaMakam.metin': 'Sertifikayı imzalayan makam tanınmıyor. Bağlantıya araya girilmiş olabilir.',
    'hata.cokme.baslik': 'Sekme yanıt vermeyi bıraktı',
    'hata.cokme.metin': 'Sayfa beklenmedik şekilde kapandı.',
    'hata.bilinmeyen.baslik': 'Bu sayfa açılamadı',
    'hata.bilinmeyen.metin': 'Sayfa yüklenirken bilinmeyen bir sorun oluştu.',
    'yenisekme.ara': 'Ara',
    'yenisekme.sik': 'Sık gidilenler',
    'yenisekme.oneCikan': 'Öne çıkan',
    'yenisekme.kisayolEkle': '+ Kısayol ekle',
    'yenisekme.kisayolIpucu': 'ornek.com — eklemek için Enter',
    'yenisekme.gecersizAdres': 'Geçerli bir adres yazın',
    'yenisekme.kisayol': 'Kısayol',
    'yenisekme.bosNot': 'Gezindikçe en çok girdiğiniz siteler burada listelenecek.',
    'yenisekme.engellendi': 'Girginos Browser bugüne kadar {n} izleyici isteğini engelledi.',
    'yenisekme.engelleyiciAcik': 'İzleyici engelleyici açık. Engellenen istekler burada sayılacak.',
    /* --- adres onerileri --- */
    'oneri.ara': '{motor} ile ara',
    'oneri.adreseGit': 'Adrese git',
    /* --- gorunum --- */
    'ayar.tema': 'Görünüm',
    'ayar.temaAciklama': 'Arayüz, iç sayfalar ve menüler bu seçime göre renklenir.',
    'ayar.temaSistem': 'Sistemle aynı',
    'ayar.temaAcik': 'Açık',
    'ayar.temaKoyu': 'Koyu',
    /* --- katman: izin kutusu --- */
    'dialog.izinIstiyor': 'şunu istiyor:',
    'izin.storage-access': 'depolama erişimi',
    /* --- site izin duvari --- */
    'panel.siteIzinleri': 'Site izinleri',
    'izin.siteYok': 'Bu sayfa için izin ayarı yok.',
    'izin.durumSor': 'Sor',
    'izin.durumIzin': 'İzin ver',
    'izin.durumRet': 'Reddet',
    'izin.varsayilanEk': 'varsayılan',
    'izin.siteKarari': 'Bu site için siz karar verdiniz.',
    'izin.varsayilanIzleniyor': 'Genel varsayılan uygulanıyor.',
    'izin.bilinmeyen': 'bu izin ({ad})'
  }
};
