'use strict';

module.exports = {
  ad: '简体中文',
  yon: 'ltr',
  yerel: 'zh-CN',
  metin: {
    'menu.dosya': '文件',
    'menu.yeniSekme': '新建标签页',
    'menu.sekmeyiKapat': '关闭标签页',
    'menu.adresCubugu': '跳到地址栏',
    'menu.sayfadaBul': '在页面中查找',
    'menu.cikis': '退出',
    'menu.duzen': '编辑',
    'menu.geriAl': '撤销',
    'menu.yinele': '重做',
    'menu.kes': '剪切',
    'menu.kopyala': '复制',
    'menu.yapistir': '粘贴',
    'menu.tumunuSec': '全选',
    'menu.gorunum': '视图',
    'menu.yenile': '重新加载',
    'menu.onbelleksizYenile': '忽略缓存重新加载',
    'menu.yakinlastir': '放大',
    'menu.uzaklastir': '缩小',
    'menu.normalBoyut': '实际大小',
    'menu.tamEkran': '全屏',
    'menu.gelistirici': '开发者工具',
    'menu.arayuzGelistirici': '界面开发者工具',
    'menu.gecmis': '历史记录',
    'menu.geri': '后退',
    'menu.ileri': '前进',
    'menu.gecmisiGoster': '显示历史记录',
    'menu.indirilenler': '下载内容',
    'menu.yerImleri': '书签',
    'menu.yerImiEkle': '将此页加入书签',
    'menu.yerImleriniGoster': '显示书签',
    'menu.yerImleriCubugu': '书签栏',
    'menu.sekmeler': '标签页',
    'menu.sonrakiSekme': '下一个标签页',
    'menu.oncekiSekme': '上一个标签页',
    'menu.nSekme': '第 {n} 个标签页',
    'menu.sonSekme': '最后一个标签页',
    'menu.yardim': '帮助',
    'menu.ayarlar': '设置',
    'menu.hakkinda': '关于 Girginos Browser',
    'hakkinda.detay': '注重隐私的浏览器。',
    'menu.yazdir': '打印…',
    'menu.sayfayiKaydet': '网页另存为…',
    'menu.digerAraclar': '更多工具',
    'menu.yakinlastirma': '缩放',
    'menu.veriSil': '删除浏览数据…',
    'arac.menu': '菜单',

    'baglam.baglantiYeniSekme': '在新标签页中打开链接',
    'baglam.baglantiKopyala': '复制链接地址',
    'baglam.gorselYeniSekme': '在新标签页中打开图片',
    'baglam.gorselKopyala': '复制图片地址',
    'baglam.gorselKaydet': '保存图片',
    'baglam.ara': '搜索“{q}”',
    'baglam.kaynak': '查看页面源代码',
    'baglam.incele': '检查元素',

    'dialog.iptal': '取消',
    'dialog.ac': '打开',
    'dialog.disBaslik': '离开 Girginos Browser',
    'dialog.disMesaj': '此“{sema}”链接将在其他应用中打开。',
    'dialog.reddet': '阻止',
    'dialog.izinVer': '允许',
    'dialog.izinBaslik': '权限请求',
    'dialog.izinMesaj': '{origin} 请求使用：',
    'dialog.izinHatirla': '记住我对该网站的选择',
    'dialog.calistirBaslik': '该文件是可执行文件',
    'dialog.calistirMesaj': '此文件可能会危害您的计算机。',
    'dialog.calistirDevam': '仍要运行',
    'dialog.kaynak': '来源',

    'izin.notifications': '发送通知',
    'izin.geolocation': '获取您的位置',
    'izin.media': '摄像头和麦克风',
    'izin.midi': 'MIDI 设备',
    'izin.midiSysex': 'MIDI 设备',
    'izin.clipboard-read': '读取剪贴板',
    'izin.display-capture': '共享屏幕',
    'izin.openExternal': '打开其他应用',
    'izin.idle-detection': '空闲检测',
    'izin.pointerLock': '锁定鼠标指针',
    'izin.fullscreen': '全屏',

    'arac.geri': '后退',
    'arac.ileri': '前进',
    'arac.yenile': '重新加载',
    'arac.durdur': '停止',
    'arac.anasayfa': '主页',
    'arac.yeniSekme': '新建标签页',
    'arac.sekmeyiKapat': '关闭标签页',
    'arac.gecmis': '历史记录',
    'arac.indirilenler': '下载内容',
    'arac.ayarlar': '设置',
    'arac.adresIpucu': '搜索或输入网址',
    'arac.yerImiEkle': '添加书签',
    'arac.yerImiCikar': '移除书签',
    'arac.kalkanAcik': '已拦截 {n} 个跟踪器 — 点击关闭',
    'arac.kalkanKapali': '此网站已关闭拦截 — 点击开启',
    'arac.guvenli': '连接已加密（HTTPS）',
    'arac.guvensiz': '连接未加密',
    'arac.yeniSekmeBaslik': '新建标签页',
    'arac.adsiz': '无标题',

    'bul.ipucu': '在页面中查找',
    'bul.onceki': '上一个',
    'bul.sonraki': '下一个',
    'bul.kapat': '关闭',

    'panel.gecmis': '历史记录',
    'panel.yerImleri': '书签',
    'panel.indirilenler': '下载内容',
    'panel.ayarlar': '设置',
    'panel.kapat': '关闭面板',
    'panel.kaldir': '移除',
    'gecmis.ara': '搜索历史记录',
    'gecmis.temizle': '清除历史记录',
    'gecmis.bos': '历史记录为空。',
    'gecmis.eslesmeYok': '没有匹配的记录。',
    'gecmis.bugun': '今天',
    'gecmis.dun': '昨天',
    'yerimi.bos': '您还没有书签。',
    'yerimi.cubukBos': '暂无书签 — 按 Ctrl+D 添加此页',
    'yerimi.tumu': '全部书签',
    'yerimi.ac': '打开',
    'yerimi.yeniSekmedeAc': '在新标签页中打开',
    'yerimi.adresiKopyala': '复制网址',
    'yerimi.duzenle': '重命名…',
    'yerimi.cubuguGizle': '隐藏书签栏',

    'indirme.bos': '暂无下载。',
    'indirme.devam': '下载中',
    'indirme.tamam': '已完成',
    'indirme.iptal': '已取消',
    'indirme.hata': '失败',
    'indirme.kesildi': '已中断',
    'indirme.ac': '打开',
    'indirme.klasor': '在文件夹中显示',
    'indirme.tumunuGoster': '查看全部',

    'ayar.engellenenSayi': '已拦截的跟踪器',
    'ayar.yukluAlan': '从列表加载的域名',
    'ayar.yerImiSayi': '书签',
    'ayar.bolumArama': '搜索与启动',
    'ayar.dil': '语言',
    'ayar.dilAciklama': '菜单、面板和错误页使用此语言。',
    'ayar.dilSistem': '系统语言',
    'ayar.aramaMotoru': '搜索引擎',
    'ayar.aramaMotoruAciklama': '在地址栏中输入的搜索将发送到这里。',
    'ayar.anasayfa': '主页',
    'ayar.anasayfaAciklama': '主页按钮打开的网址。',
    'ayar.anasayfaIpucu': '留空则使用新标签页',
    'ayar.bolumGizlilik': '隐私',
    'ayar.engelleyici': '跟踪器与广告拦截',
    'ayar.engelleyiciAciklama': '取消对已知广告和跟踪域名的请求。',
    'ayar.dnt': '发送“请勿跟踪”信号',
    'ayar.dntAciklama': '为每个请求添加 DNT 和 Sec-GPC 标头。',
    'ayar.gecmisiKaydet': '保存历史记录',
    'ayar.gecmisiKaydetAciklama': '关闭时，访问过的页面不会写入磁盘。',
    'ayar.cerezler': 'Cookie 和缓存',
    'ayar.cerezlerAciklama': '删除所有网站的 Cookie、本地存储和缓存。',
    'ayar.veriTemizle': '清除数据',
    'ayar.temizleniyor': '正在清除…',
    'ayar.temizlendi': '已清除',
    'ayar.siteIzinleri': '网站权限',
    'ayar.siteIzinleriAciklama': '删除已记住的位置、摄像头和通知选择，以及拦截例外。',
    'ayar.izinSifirla': '重置网站权限',
    'ayar.sifirlandi': '已重置',
    'ayar.bolumListeler': '过滤列表',
    'ayar.listeKullan': '使用已下载的列表',
    'ayar.listeKullanAciklama': '同时拦截 EasyList 等列表中的域名。关闭时仅使用内置列表。',
    'ayar.otomatikGuncelle': '自动更新',
    'ayar.otomatikGuncelleAciklama': '列表按其声明的周期在后台刷新（通常每 4 天一次）。',
    'ayar.listeYenile': '刷新列表',
    'ayar.listeYenileAciklama': '立即重新下载全部列表。',
    'ayar.simdiGuncelle': '立即更新',
    'ayar.guncelleniyor': '正在更新…',
    'ayar.listeEkle': '添加自己的列表',
    'ayar.listeEkleAciklama': 'Adblock Plus、hosts 或纯域名格式的 https 地址。',
    'ayar.listeEkleIpucu': 'https://... 过滤列表地址',
    'ayar.ekle': '添加',
    'ayar.ekleniyor': '正在添加…',
    'ayar.listeKaldir': '移除',
    'ayar.listeIndirilmedi': '尚未下载',
    'ayar.listeHata': '更新失败：{hata}',
    'ayar.listeDurum': '{n} 个域名 · {ne}更新',
    'ayar.bugun': '今天',
    'ayar.dun': '昨天',
    'ayar.gunOnce': '{n} 天前',
    'ayar.bolumIzinler': '权限请求',
    'ayar.izinSor': '每次询问',
    'ayar.izinVer': '始终允许',
    'ayar.izinRet': '始终阻止',
    'ayar.izinSatir': '当网站请求{izin}时该怎么办？',
    'ayar.bolumGorunum': '外观',
    'ayar.yerImleriCubugu': '书签栏',
    'ayar.yerImleriCubuguAciklama': '在工具栏下方显示书签。',
    'ayar.yenidenBaslat': '请重启 Girginos Browser 以应用语言更改。',

    'liste.easylist': '广告',
    'liste.easyprivacy': '跟踪器',
    'liste.hataHttps': '只能添加 https:// 地址。',
    'liste.hataVar': '该列表已添加。',
    /* --- site bilgisi menusu --- */
    'site.baglantiGuvenli': '连接是安全的',
    'site.baglantiGuvensiz': '连接不安全',
    'site.guvensizUyari': '您在此页面输入的信息将以未加密方式发送。',
    'site.sertifikaVeren': '颁发者：{ad}',
    'site.sertifikaSahip': '颁发给：{ad}',
    'site.sertifikaGecerlilik': '有效期：{bas} – {bit}',
    'site.parmakIzi': '复制指纹',
    'site.sertifikaYok': '无证书信息',
    'site.cerezler': 'Cookie 和网站数据',
    'site.cerezSayisi': '{n} 个 Cookie',
    'site.veriSil': '删除此网站的数据',
    'site.engelleyici': '跟踪器拦截',
    'site.izinSifirla': '重置此网站的权限',
    'site.ayarlar': '网站设置',
    /* --- guncelleme --- */
    'menu.guncellemeDenetle': '检查更新',
    'ayar.bolumGuncelleme': '更新',
    'ayar.surum': '版本',
    'ayar.guncellemeKontrolEt': '立即检查',
    'ayar.guncellemeIndirDugme': '下载',
    'ayar.guncellemeKur': '重启并安装',
    'ayar.guncellemeOtoKontrol': '自动检查更新',
    'ayar.guncellemeOtoKontrolAciklama': '启动时以及每 6 小时检查一次已签名的发布信息。',
    'ayar.guncellemeOtoIndir': '自动下载',
    'ayar.guncellemeOtoIndirAciklama': '新版本会在后台下载；安装仍需您确认。',
    'ayar.guncellemeKanal': '更新通道',
    'ayar.guncellemeKanalAciklama': '测试版通道更早获得新功能，测试较少。',
    'ayar.kanalKararli': '稳定版',
    'ayar.kanalBeta': '测试版',
    'guncelleme.kapali': '更新已关闭：未配置发布密钥或更新地址。',
    'guncelleme.paketlenmemis': '正在以源码方式运行；更新仅对已安装版本生效。',
    'guncelleme.bosta': '尚未检查。',
    'guncelleme.kontrol': '正在检查…',
    'guncelleme.guncel': '您使用的已是最新版本。',
    'guncelleme.bulundu': '{surum} 版本已发布。',
    'guncelleme.iniyor': '正在下载… {n}%',
    'guncelleme.hazir': '{surum} 已准备好安装。',
    'guncelleme.hata': '检查失败：{sebep}',
    /* --- yeni sekme ve hata sayfasi --- */
    'sayfa.tekrarDene': '重试',
    'sayfa.oneriYenile': '重新加载页面',
    'sayfa.oneriAdres': '检查网址是否有拼写错误',
    'sayfa.oneriBaglanti': '检查您的网络连接',
    'sayfa.oneriBilgiGirme': '请勿在此页输入敏感信息',
    'hata.dns.baslik': '找不到服务器',
    'hata.dns.metin': '无法将此地址解析为 IP。域名可能拼写错误或已下线。',
    'hata.cevrimdisi.baslik': '没有网络连接',
    'hata.cevrimdisi.metin': '您的设备似乎未连接到网络。',
    'hata.baglanti.baslik': '无法连接',
    'hata.baglanti.metin': '服务器拒绝了连接，或连接意外中断。',
    'hata.zamanAsimi.baslik': '连接超时',
    'hata.zamanAsimi.metin': '服务器未在合理时间内响应。',
    'hata.sertifikaAd.baslik': '证书与此网站不符',
    'hata.sertifikaAd.metin': '服务器证书中的域名与您输入的地址不一致。',
    'hata.sertifikaSure.baslik': '证书已过期',
    'hata.sertifikaSure.metin': '服务器的安全证书已失效。请同时检查设备日期。',
    'hata.sertifikaMakam.baslik': '无法验证证书',
    'hata.sertifikaMakam.metin': '签发该证书的机构未被识别。连接可能被拦截。',
    'hata.cokme.baslik': '标签页已停止响应',
    'hata.cokme.metin': '页面意外关闭。',
    'hata.bilinmeyen.baslik': '无法打开此页面',
    'hata.bilinmeyen.metin': '加载页面时发生未知问题。',
    'yenisekme.ara': '搜索',
    'yenisekme.sik': '常去网站',
    'yenisekme.oneCikan': '精选',
    'yenisekme.kisayolEkle': '+ 添加快捷方式',
    'yenisekme.kisayolIpucu': 'example.com — 按 Enter 添加',
    'yenisekme.gecersizAdres': '请输入有效的网址',
    'yenisekme.kisayol': '快捷方式',
    'yenisekme.bosNot': '随着浏览，您最常访问的网站会显示在这里。',
    'yenisekme.engellendi': 'Girginos Browser 至今已拦截 {n} 个跟踪请求。',
    'yenisekme.engelleyiciAcik': '跟踪拦截已开启。被拦截的请求将在此统计。',
    /* --- adres onerileri --- */
    'oneri.ara': '使用 {motor} 搜索',
    'oneri.adreseGit': '前往该网址',
    /* --- gorunum --- */
    'ayar.tema': '外观',
    'ayar.temaAciklama': '界面、内置页面和菜单都会跟随此设置。',
    'ayar.temaSistem': '跟随系统',
    'ayar.temaAcik': '浅色',
    'ayar.temaKoyu': '深色',
    /* --- katman: izin kutusu --- */
    'dialog.izinIstiyor': '请求使用：',
    'izin.storage-access': '存储访问权限'
  }
};
